APP_STL := gnustl_static

APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic

NDK_TOOLCHAIN_VERSION := 4.9

ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1 -DCC_LUA_ENGINE_ENABLED=1 -DMD5_FILE -DMD5_FILE_LOG -DUSE_AUDIO_ENGINE
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG -DCC_LUA_ENGINE_ENABLED=1 -DMD5_FILE -DUSE_AUDIO_ENGINE
  APP_OPTIM := release
endif
