--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create green_btn
local green_btn = ccui.Button:create()
green_btn:ignoreContentAdaptWithSize(false)
green_btn:loadTextureNormal("ui/button/green_btn.png",0)
green_btn:loadTexturePressed("ui/button/green_btn.png",0)
green_btn:loadTextureDisabled("Default/Button_Disable.png",0)
green_btn:setTitleFontSize(18)
green_btn:setTitleText("绿色按钮")
green_btn:setTitleColor({r = 65, g = 65, b = 70})
green_btn:setScale9Enabled(true)
green_btn:setCapInsets({x = 15, y = 11, width = 168, height = 48})
green_btn:setLayoutComponentEnabled(true)
green_btn:setName("green_btn")
green_btn:setTag(17)
green_btn:setCascadeColorEnabled(true)
green_btn:setCascadeOpacityEnabled(true)
green_btn:setPosition(459.0000, 478.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(green_btn)
layout:setPositionPercentX(0.4781)
layout:setPositionPercentY(0.7469)
layout:setPercentWidth(0.2063)
layout:setPercentHeight(0.1094)
layout:setSize({width = 198.0000, height = 70.0000})
layout:setLeftMargin(360.0000)
layout:setRightMargin(402.0000)
layout:setTopMargin(127.0000)
layout:setBottomMargin(443.0000)
Scene:addChild(green_btn)

--Create toggle_btn
local toggle_btn=cc.Node:create()
toggle_btn:setName("toggle_btn")
toggle_btn:setTag(20)
toggle_btn:setCascadeColorEnabled(true)
toggle_btn:setCascadeOpacityEnabled(true)
toggle_btn:setPosition(458.0000, 385.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(toggle_btn)
layout:setPositionPercentX(0.4771)
layout:setPositionPercentY(0.6016)
layout:setLeftMargin(458.0000)
layout:setRightMargin(502.0000)
layout:setTopMargin(255.0000)
layout:setBottomMargin(385.0000)
Scene:addChild(toggle_btn)

--Create switch_btn
local switch_btn=cc.Node:create()
switch_btn:setName("switch_btn")
switch_btn:setTag(21)
switch_btn:setCascadeColorEnabled(true)
switch_btn:setCascadeOpacityEnabled(true)
switch_btn:setPosition(459.0000, 306.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(switch_btn)
layout:setPositionPercentX(0.4781)
layout:setPositionPercentY(0.4781)
layout:setLeftMargin(459.0000)
layout:setRightMargin(501.0000)
layout:setTopMargin(334.0000)
layout:setBottomMargin(306.0000)
Scene:addChild(switch_btn)

--Create CheckBox_1
local CheckBox_1 = ccui.CheckBox:create()
CheckBox_1:ignoreContentAdaptWithSize(false)
CheckBox_1:loadTextureBackGround("ui/button/choose_bg.png",0)
CheckBox_1:loadTextureBackGroundSelected("ui/button/choose_bg.png",0)
CheckBox_1:loadTextureBackGroundDisabled("Default/CheckBox_Disable.png",0)
CheckBox_1:loadTextureFrontCross("ui/button/choose.png",0)
CheckBox_1:loadTextureFrontCrossDisabled("Default/CheckBoxNode_Disable.png",0)
CheckBox_1:setSelected(true)
CheckBox_1:setLayoutComponentEnabled(true)
CheckBox_1:setName("CheckBox_1")
CheckBox_1:setTag(22)
CheckBox_1:setCascadeColorEnabled(true)
CheckBox_1:setCascadeOpacityEnabled(true)
CheckBox_1:setPosition(460.0000, 226.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_1)
layout:setPositionPercentX(0.4792)
layout:setPositionPercentY(0.3531)
layout:setPercentWidth(0.0417)
layout:setPercentHeight(0.0625)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(440.0000)
layout:setRightMargin(480.0000)
layout:setTopMargin(394.0000)
layout:setBottomMargin(206.0000)
Scene:addChild(CheckBox_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

