--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("PlaySceneBg.jpg",1)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(9)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(1136.0000, 640.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
Layer:addChild(Image_1)

--Create Star_1
local Star_1 = cc.Sprite:createWithSpriteFrameName("Star.png")
Star_1:setName("Star_1")
Star_1:setTag(10)
Star_1:setCascadeColorEnabled(true)
Star_1:setCascadeOpacityEnabled(true)
Star_1:setPosition(60.6672, 572.1718)
layout = ccui.LayoutComponent:bindLayoutComponent(Star_1)
layout:setPositionPercentX(0.0534)
layout:setPositionPercentY(0.8940)
layout:setSize(cc.size(44.0000, 44.0000))
layout:setLeftMargin(38.6672)
layout:setRightMargin(1053.3328)
layout:setTopMargin(45.8282)
layout:setBottomMargin(550.1718)
Layer:addChild(Star_1)

--Create livesLabel
local livesLabel = ccui.Text:create()
livesLabel:ignoreContentAdaptWithSize(true)
livesLabel:setTextAreaSize(cc.size(0, 0))
livesLabel:setFontSize(32)
livesLabel:setString([[5]])
livesLabel:enableShadow(cc.c4b(72, 133, 78, 255), cc.size(2.0000, -2.0000), 0)
livesLabel:setLayoutComponentEnabled(true)
livesLabel:setName("livesLabel")
livesLabel:setTag(11)
livesLabel:setCascadeColorEnabled(true)
livesLabel:setCascadeOpacityEnabled(true)
livesLabel:setPosition(99.0000, 575.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(livesLabel)
layout:setPositionPercentX(0.0871)
layout:setPositionPercentY(0.8984)
layout:setSize(cc.size(16.0000, 33.0000))
layout:setLeftMargin(91.0000)
layout:setRightMargin(1029.0000)
layout:setTopMargin(48.5000)
layout:setBottomMargin(558.5000)
Layer:addChild(livesLabel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

