--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create page_view
local page_view = ccui.PageView:create()
page_view:ignoreContentAdaptWithSize(false)
page_view:setClippingEnabled(true)
page_view:setBackGroundColorType(1)
page_view:setBackGroundColor({r = 150, g = 150, b = 100})
page_view:setBackGroundColorOpacity(102)
page_view:setLayoutComponentEnabled(true)
page_view:setName("page_view")
page_view:setTag(22)
page_view:setCascadeColorEnabled(true)
page_view:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(page_view)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 960.0000, height = 640.0000})
Scene:addChild(page_view)

--Create page1
local page1 = ccui.Layout:create()
page1:ignoreContentAdaptWithSize(false)
page1:setClippingEnabled(false)
page1:setBackGroundColorType(1)
page1:setBackGroundColor({r = 150, g = 200, b = 255})
page1:setBackGroundColorOpacity(102)
page1:setTouchEnabled(true);
page1:setLayoutComponentEnabled(true)
page1:setName("page1")
page1:setTag(33)
page1:setCascadeColorEnabled(true)
page1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(page1)
layout:setPercentWidth(0.3333)
layout:setPercentHeight(1.0000)
layout:setSize({width = 960.0000, height = 640.0000})
layout:setRightMargin(1920.0000)
page_view:addPage(page1)

--Create Text_4
local Text_4 = ccui.Text:create()
Text_4:ignoreContentAdaptWithSize(true)
Text_4:setTextAreaSize({width = 0, height = 0})
Text_4:setFontSize(32)
Text_4:setString([[Page1]])
Text_4:setLayoutComponentEnabled(true)
Text_4:setName("Text_4")
Text_4:setTag(36)
Text_4:setCascadeColorEnabled(true)
Text_4:setCascadeOpacityEnabled(true)
Text_4:setPosition(471.5281, 327.0945)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4)
layout:setPositionPercentX(0.4912)
layout:setPositionPercentY(0.5111)
layout:setPercentWidth(0.0833)
layout:setPercentHeight(0.0516)
layout:setSize({width = 80.0000, height = 33.0000})
layout:setLeftMargin(431.5281)
layout:setRightMargin(448.4719)
layout:setTopMargin(296.4055)
layout:setBottomMargin(310.5945)
page1:addChild(Text_4)

--Create page2
local page2 = ccui.Layout:create()
page2:ignoreContentAdaptWithSize(false)
page2:setClippingEnabled(false)
page2:setBackGroundColorType(1)
page2:setBackGroundColor({r = 150, g = 200, b = 255})
page2:setBackGroundColorOpacity(102)
page2:setTouchEnabled(true);
page2:setLayoutComponentEnabled(true)
page2:setName("page2")
page2:setLocalZOrder(1)
page2:setTag(34)
page2:setCascadeColorEnabled(true)
page2:setCascadeOpacityEnabled(true)
page2:setPosition(960.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(page2)
layout:setPositionPercentX(0.3333)
layout:setPercentWidth(0.3333)
layout:setPercentHeight(1.0000)
layout:setSize({width = 960.0000, height = 640.0000})
layout:setLeftMargin(960.0000)
layout:setRightMargin(960.0000)
page_view:addPage(page2)

--Create Text_4_0
local Text_4_0 = ccui.Text:create()
Text_4_0:ignoreContentAdaptWithSize(true)
Text_4_0:setTextAreaSize({width = 0, height = 0})
Text_4_0:setFontSize(32)
Text_4_0:setString([[Page2]])
Text_4_0:setLayoutComponentEnabled(true)
Text_4_0:setName("Text_4_0")
Text_4_0:setTag(37)
Text_4_0:setCascadeColorEnabled(true)
Text_4_0:setCascadeOpacityEnabled(true)
Text_4_0:setPosition(481.5281, 317.0945)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4_0)
layout:setPositionPercentX(0.5016)
layout:setPositionPercentY(0.4955)
layout:setPercentWidth(0.0833)
layout:setPercentHeight(0.0516)
layout:setSize({width = 80.0000, height = 33.0000})
layout:setLeftMargin(441.5281)
layout:setRightMargin(438.4719)
layout:setTopMargin(306.4055)
layout:setBottomMargin(300.5945)
page2:addChild(Text_4_0)

--Create page3
local page3 = ccui.Layout:create()
page3:ignoreContentAdaptWithSize(false)
page3:setClippingEnabled(false)
page3:setBackGroundColorType(1)
page3:setBackGroundColor({r = 150, g = 200, b = 255})
page3:setBackGroundColorOpacity(102)
page3:setTouchEnabled(true);
page3:setLayoutComponentEnabled(true)
page3:setName("page3")
page3:setLocalZOrder(2)
page3:setTag(35)
page3:setCascadeColorEnabled(true)
page3:setCascadeOpacityEnabled(true)
page3:setPosition(1920.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(page3)
layout:setPositionPercentX(0.6667)
layout:setPercentWidth(0.3333)
layout:setPercentHeight(1.0000)
layout:setSize({width = 960.0000, height = 640.0000})
layout:setLeftMargin(1920.0000)
page_view:addPage(page3)

--Create Text_4_0_0
local Text_4_0_0 = ccui.Text:create()
Text_4_0_0:ignoreContentAdaptWithSize(true)
Text_4_0_0:setTextAreaSize({width = 0, height = 0})
Text_4_0_0:setFontSize(32)
Text_4_0_0:setString([[Page3]])
Text_4_0_0:setLayoutComponentEnabled(true)
Text_4_0_0:setName("Text_4_0_0")
Text_4_0_0:setTag(38)
Text_4_0_0:setCascadeColorEnabled(true)
Text_4_0_0:setCascadeOpacityEnabled(true)
Text_4_0_0:setPosition(491.5281, 307.0946)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4_0_0)
layout:setPositionPercentX(0.5120)
layout:setPositionPercentY(0.4798)
layout:setPercentWidth(0.0833)
layout:setPercentHeight(0.0516)
layout:setSize({width = 80.0000, height = 33.0000})
layout:setLeftMargin(451.5281)
layout:setRightMargin(428.4719)
layout:setTopMargin(316.4054)
layout:setBottomMargin(290.5946)
page3:addChild(Text_4_0_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

