--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create menu_list
local menu_list = ccui.ListView:create()
menu_list:setDirection(1)
menu_list:setGravity(0)
menu_list:ignoreContentAdaptWithSize(false)
menu_list:setClippingEnabled(false)
menu_list:setBackGroundColorOpacity(102)
menu_list:setLayoutComponentEnabled(true)
menu_list:setName("menu_list")
menu_list:setTag(4)
menu_list:setCascadeColorEnabled(true)
menu_list:setCascadeOpacityEnabled(true)
menu_list:setPosition(284.0350, 117.3691)
layout = ccui.LayoutComponent:bindLayoutComponent(menu_list)
layout:setPositionPercentX(0.2959)
layout:setPositionPercentY(0.1834)
layout:setPercentWidth(0.4167)
layout:setPercentHeight(0.6875)
layout:setSize({width = 400.0000, height = 440.0000})
layout:setLeftMargin(284.0350)
layout:setRightMargin(275.9650)
layout:setTopMargin(82.6309)
layout:setBottomMargin(117.3691)
Scene:addChild(menu_list)

--Create menu_btn
local menu_btn = ccui.Button:create()
menu_btn:ignoreContentAdaptWithSize(false)
menu_btn:loadTextureNormal("Default/Button_Normal.png",0)
menu_btn:loadTexturePressed("Default/Button_Press.png",0)
menu_btn:loadTextureDisabled("Default/Button_Disable.png",0)
menu_btn:setTitleFontSize(14)
menu_btn:setTitleText("Button")
menu_btn:setTitleColor({r = 65, g = 65, b = 70})
menu_btn:setScale9Enabled(true)
menu_btn:setCapInsets({x = 15, y = 11, width = 16, height = 14})
menu_btn:setLayoutComponentEnabled(true)
menu_btn:setName("menu_btn")
menu_btn:setTag(5)
menu_btn:setCascadeColorEnabled(true)
menu_btn:setCascadeOpacityEnabled(true)
menu_btn:setPosition(96.1106, 404.5170)
menu_btn:setColor({r = 0, g = 128, b = 0})
if callBackProvider~=nil then
      menu_btn:addClickEventListener(callBackProvider("TestLuaScene.lua", menu_btn, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(menu_btn)
layout:setPositionPercentX(0.1001)
layout:setPositionPercentY(0.6321)
layout:setPercentWidth(0.2083)
layout:setPercentHeight(0.0625)
layout:setSize({width = 200.0000, height = 40.0000})
layout:setLeftMargin(-3.8894)
layout:setRightMargin(763.8894)
layout:setTopMargin(215.4830)
layout:setBottomMargin(384.5170)
Scene:addChild(menu_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

