--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 125, g = 201, b = 242})
panel:setBackGroundColorOpacity(103)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(104)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8594)
layout:setPercentHeight(0.8803)
layout:setSize({width = 550.0000, height = 1000.0000})
layout:setLeftMargin(45.0000)
layout:setRightMargin(45.0000)
layout:setTopMargin(68.0000)
layout:setBottomMargin(68.0000)
Scene:addChild(panel)

--Create input_bg
local input_bg = ccui.ImageView:create()
input_bg:ignoreContentAdaptWithSize(false)
input_bg:loadTexture("res/input_bg.png",0)
input_bg:setScale9Enabled(true)
input_bg:setCapInsets({x = 5, y = 5, width = 21, height = 21})
input_bg:setLayoutComponentEnabled(true)
input_bg:setName("input_bg")
input_bg:setTag(93)
input_bg:setCascadeColorEnabled(true)
input_bg:setCascadeOpacityEnabled(true)
input_bg:setPosition(224.7734, 31.7810)
layout = ccui.LayoutComponent:bindLayoutComponent(input_bg)
layout:setPositionPercentX(0.4087)
layout:setPositionPercentY(0.0318)
layout:setPercentWidth(0.8182)
layout:setPercentHeight(0.0600)
layout:setSize({width = 450.0000, height = 60.0000})
layout:setLeftMargin(-0.2266)
layout:setRightMargin(100.2266)
layout:setTopMargin(938.2190)
layout:setBottomMargin(1.7810)
panel:addChild(input_bg)

--Create listView
local listView = ccui.ListView:create()
listView:setDirection(1)
listView:setGravity(0)
listView:ignoreContentAdaptWithSize(false)
listView:setClippingEnabled(true)
listView:setBackGroundColorOpacity(102)
listView:setLayoutComponentEnabled(true)
listView:setName("listView")
listView:setTag(94)
listView:setCascadeColorEnabled(true)
listView:setCascadeOpacityEnabled(true)
listView:setPosition(1.0002, 64.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(listView)
layout:setPositionPercentX(0.0018)
layout:setPositionPercentY(0.0640)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.9310)
layout:setSize({width = 550.0000, height = 931.0000})
layout:setLeftMargin(1.0002)
layout:setRightMargin(-1.0002)
layout:setTopMargin(4.9999)
layout:setBottomMargin(64.0001)
panel:addChild(listView)

--Create btn_clear
local btn_clear = ccui.Button:create()
btn_clear:ignoreContentAdaptWithSize(false)
btn_clear:loadTextureNormal("Default/Button_Normal.png",0)
btn_clear:loadTexturePressed("Default/Button_Press.png",0)
btn_clear:loadTextureDisabled("Default/Button_Disable.png",0)
btn_clear:setTitleFontSize(28)
btn_clear:setTitleText("Clear")
btn_clear:setTitleColor({r = 65, g = 65, b = 70})
btn_clear:setScale9Enabled(true)
btn_clear:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_clear:setLayoutComponentEnabled(true)
btn_clear:setName("btn_clear")
btn_clear:setTag(95)
btn_clear:setCascadeColorEnabled(true)
btn_clear:setCascadeOpacityEnabled(true)
btn_clear:setPosition(375.0255, 963.9111)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_clear)
layout:setPositionPercentX(0.6819)
layout:setPositionPercentY(0.9639)
layout:setPercentWidth(0.1818)
layout:setPercentHeight(0.0500)
layout:setSize({width = 100.0000, height = 50.0000})
layout:setLeftMargin(325.0255)
layout:setRightMargin(124.9745)
layout:setTopMargin(11.0889)
layout:setBottomMargin(938.9111)
panel:addChild(btn_clear)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("Default/Button_Normal.png",0)
btn_close:loadTexturePressed("Default/Button_Press.png",0)
btn_close:loadTextureDisabled("Default/Button_Disable.png",0)
btn_close:setTitleFontSize(28)
btn_close:setTitleText("Close")
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(96)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(493.1856, 963.9111)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8967)
layout:setPositionPercentY(0.9639)
layout:setPercentWidth(0.1818)
layout:setPercentHeight(0.0500)
layout:setSize({width = 100.0000, height = 50.0000})
layout:setLeftMargin(443.1856)
layout:setRightMargin(6.8144)
layout:setTopMargin(11.0889)
layout:setBottomMargin(938.9111)
panel:addChild(btn_close)

--Create btn_send
local btn_send = ccui.Button:create()
btn_send:ignoreContentAdaptWithSize(false)
btn_send:loadTextureNormal("Default/Button_Normal.png",0)
btn_send:loadTexturePressed("Default/Button_Press.png",0)
btn_send:loadTextureDisabled("Default/Button_Disable.png",0)
btn_send:setTitleFontSize(28)
btn_send:setTitleText("Send")
btn_send:setTitleColor({r = 65, g = 65, b = 70})
btn_send:setScale9Enabled(true)
btn_send:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_send:setLayoutComponentEnabled(true)
btn_send:setName("btn_send")
btn_send:setTag(97)
btn_send:setCascadeColorEnabled(true)
btn_send:setCascadeOpacityEnabled(true)
btn_send:setPosition(497.5530, 31.4891)
btn_send:setColor({r = 19, g = 215, b = 94})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_send)
layout:setPositionPercentX(0.9046)
layout:setPositionPercentY(0.0315)
layout:setPercentWidth(0.1818)
layout:setPercentHeight(0.0550)
layout:setSize({width = 100.0000, height = 55.0000})
layout:setLeftMargin(447.5530)
layout:setRightMargin(2.4470)
layout:setTopMargin(941.0109)
layout:setBottomMargin(3.9891)
panel:addChild(btn_send)

--Create text_template
local text_template = ccui.Text:create()
text_template:ignoreContentAdaptWithSize(true)
text_template:setTextAreaSize({width = 0, height = 0})
text_template:setFontSize(18)
text_template:setString([[模板文字]])
text_template:setLayoutComponentEnabled(true)
text_template:setName("text_template")
text_template:setTag(98)
text_template:setCascadeColorEnabled(true)
text_template:setCascadeOpacityEnabled(true)
text_template:setVisible(false)
text_template:setPosition(36.0000, 922.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text_template)
layout:setPositionPercentX(0.0655)
layout:setPositionPercentY(0.9220)
layout:setPercentWidth(0.1309)
layout:setPercentHeight(0.0180)
layout:setSize({width = 72.0000, height = 18.0000})
layout:setRightMargin(478.0000)
layout:setTopMargin(69.0000)
layout:setBottomMargin(913.0000)
panel:addChild(text_template)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

