--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create popup_bg_4
local popup_bg_4 = cc.Sprite:create("ui/tetris/power/power_fail_bg2.png")
popup_bg_4:setName("popup_bg_4")
popup_bg_4:setTag(51)
popup_bg_4:setCascadeColorEnabled(true)
popup_bg_4:setCascadeOpacityEnabled(true)
popup_bg_4:setPosition(320.0000, 644.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(popup_bg_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5669)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6294)
layout:setSize({width = 640.0000, height = 715.0000})
layout:setTopMargin(134.5000)
layout:setBottomMargin(286.5000)
popup_bg_4:setBlendFunc({src = 1, dst = 771})
panel:addChild(popup_bg_4)

--Create btn_powerretry
local btn_powerretry = ccui.Button:create()
btn_powerretry:ignoreContentAdaptWithSize(false)
btn_powerretry:loadTextureNormal("ui/tetris/power/power_fail_retry.png",0)
btn_powerretry:loadTexturePressed("ui/tetris/power/power_fail_retry.png",0)
btn_powerretry:loadTextureDisabled("ui/tetris/power/power_fail_retry.png",0)
btn_powerretry:setTitleFontSize(14)
btn_powerretry:setTitleColor({r = 65, g = 65, b = 70})
btn_powerretry:setScale9Enabled(true)
btn_powerretry:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_powerretry:setLayoutComponentEnabled(true)
btn_powerretry:setName("btn_powerretry")
btn_powerretry:setTag(20)
btn_powerretry:setCascadeColorEnabled(true)
btn_powerretry:setCascadeOpacityEnabled(true)
btn_powerretry:setPosition(320.0000, 134.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_powerretry)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1874)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.1203)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(538.0000)
layout:setBottomMargin(91.0000)
popup_bg_4:addChild(btn_powerretry)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("ui/tetris/power/close.png",0)
btn_close:loadTexturePressed("ui/tetris/power/close.png",0)
btn_close:loadTextureDisabled("ui/tetris/power/close.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 35, height = 43})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(279)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(558.2432, 667.4741)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8723)
layout:setPositionPercentY(0.9335)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0909)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(525.7432)
layout:setRightMargin(49.2568)
layout:setTopMargin(15.0259)
layout:setBottomMargin(634.9741)
popup_bg_4:addChild(btn_close)

--Create gem_bg
local gem_bg = cc.Sprite:create("ui/tetris/power/energy_bg2.png")
gem_bg:setName("gem_bg")
gem_bg:setTag(262)
gem_bg:setCascadeColorEnabled(true)
gem_bg:setCascadeOpacityEnabled(true)
gem_bg:setPosition(299.5347, 260.0323)
layout = ccui.LayoutComponent:bindLayoutComponent(gem_bg)
layout:setPositionPercentX(0.4680)
layout:setPositionPercentY(0.3637)
layout:setPercentWidth(0.0688)
layout:setPercentHeight(0.0615)
layout:setSize({width = 44.0000, height = 44.0000})
layout:setLeftMargin(277.5347)
layout:setRightMargin(318.4653)
layout:setTopMargin(432.9677)
layout:setBottomMargin(238.0323)
gem_bg:setBlendFunc({src = 1, dst = 771})
popup_bg_4:addChild(gem_bg)

--Create lb_reward
local lb_reward = ccui.Text:create()
lb_reward:ignoreContentAdaptWithSize(true)
lb_reward:setTextAreaSize({width = 0, height = 0})
lb_reward:setFontSize(30)
lb_reward:setString([[-1]])
lb_reward:enableShadow({r = 61, g = 136, b = 171, a = 255}, {width = 1, height = -1}, 0)
lb_reward:setLayoutComponentEnabled(true)
lb_reward:setName("lb_reward")
lb_reward:setTag(261)
lb_reward:setCascadeColorEnabled(true)
lb_reward:setCascadeOpacityEnabled(true)
lb_reward:setAnchorPoint(0.0000, 0.5000)
lb_reward:setPosition(323.2491, 260.0323)
lb_reward:setTextColor({r = 215, g = 85, b = 85})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_reward)
layout:setPositionPercentX(0.5051)
layout:setPositionPercentY(0.3637)
layout:setPercentWidth(0.0469)
layout:setPercentHeight(0.0420)
layout:setSize({width = 30.0000, height = 30.0000})
layout:setLeftMargin(323.2491)
layout:setRightMargin(286.7509)
layout:setTopMargin(439.9677)
layout:setBottomMargin(245.0323)
popup_bg_4:addChild(lb_reward)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

