--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create popup_bg_4
local popup_bg_4 = cc.Sprite:create("ui/tetris/power/power_star_bg2.png")
popup_bg_4:setName("popup_bg_4")
popup_bg_4:setTag(51)
popup_bg_4:setCascadeColorEnabled(true)
popup_bg_4:setCascadeOpacityEnabled(true)
popup_bg_4:setPosition(320.0000, 644.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(popup_bg_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5669)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6294)
layout:setSize({width = 640.0000, height = 715.0000})
layout:setTopMargin(134.5000)
layout:setBottomMargin(286.5000)
popup_bg_4:setBlendFunc({src = 1, dst = 771})
panel:addChild(popup_bg_4)

--Create btn_powerstart
local btn_powerstart = ccui.Button:create()
btn_powerstart:ignoreContentAdaptWithSize(false)
btn_powerstart:loadTextureNormal("ui/tetris/power/power_start.png",0)
btn_powerstart:loadTexturePressed("ui/tetris/power/power_start.png",0)
btn_powerstart:loadTextureDisabled("ui/tetris/power/power_start.png",0)
btn_powerstart:setTitleFontSize(14)
btn_powerstart:setTitleColor({r = 65, g = 65, b = 70})
btn_powerstart:setScale9Enabled(true)
btn_powerstart:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_powerstart:setLayoutComponentEnabled(true)
btn_powerstart:setName("btn_powerstart")
btn_powerstart:setTag(20)
btn_powerstart:setCascadeColorEnabled(true)
btn_powerstart:setCascadeOpacityEnabled(true)
btn_powerstart:setPosition(323.0001, 157.0013)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_powerstart)
layout:setPositionPercentX(0.5047)
layout:setPositionPercentY(0.2196)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.1203)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(177.0001)
layout:setRightMargin(170.9999)
layout:setTopMargin(514.9987)
layout:setBottomMargin(114.0013)
popup_bg_4:addChild(btn_powerstart)

--Create lb_armynum
local lb_armynum = ccui.TextAtlas:create([[222]],
													"ui/tetris/number.png",
													30,
													50,
													"0")
lb_armynum:setLayoutComponentEnabled(true)
lb_armynum:setName("lb_armynum")
lb_armynum:setTag(191)
lb_armynum:setCascadeColorEnabled(true)
lb_armynum:setCascadeOpacityEnabled(true)
lb_armynum:setPosition(323.3365, 551.4284)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_armynum)
layout:setPositionPercentX(0.5052)
layout:setPositionPercentY(0.7712)
layout:setPercentWidth(0.1406)
layout:setPercentHeight(0.0699)
layout:setSize({width = 90.0000, height = 50.0000})
layout:setLeftMargin(278.3365)
layout:setRightMargin(271.6635)
layout:setTopMargin(138.5716)
layout:setBottomMargin(526.4284)
popup_bg_4:addChild(lb_armynum)

--Create lb_powername
local lb_powername = ccui.Text:create()
lb_powername:ignoreContentAdaptWithSize(true)
lb_powername:setTextAreaSize({width = 0, height = 0})
lb_powername:setFontSize(32)
lb_powername:setString([[目标说明]])
lb_powername:setTextHorizontalAlignment(1)
lb_powername:setTextVerticalAlignment(1)
lb_powername:enableShadow({r = 55, g = 168, b = 245, a = 255}, {width = 1, height = -1}, 0)
lb_powername:setLayoutComponentEnabled(true)
lb_powername:setName("lb_powername")
lb_powername:setTag(221)
lb_powername:setCascadeColorEnabled(true)
lb_powername:setCascadeOpacityEnabled(true)
lb_powername:setPosition(322.0101, 472.6529)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_powername)
layout:setPositionPercentX(0.5031)
layout:setPositionPercentY(0.6611)
layout:setPercentWidth(0.2000)
layout:setPercentHeight(0.0462)
layout:setSize({width = 128.0000, height = 33.0000})
layout:setLeftMargin(258.0101)
layout:setRightMargin(253.9899)
layout:setTopMargin(225.8471)
layout:setBottomMargin(456.1529)
popup_bg_4:addChild(lb_powername)

--Create sp_target1
local sp_target1 = cc.Sprite:create("Default/Sprite.png")
sp_target1:setName("sp_target1")
sp_target1:setTag(56)
sp_target1:setCascadeColorEnabled(true)
sp_target1:setCascadeOpacityEnabled(true)
sp_target1:setPosition(227.9998, 391.8918)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_target1)
layout:setPositionPercentX(0.3562)
layout:setPositionPercentY(0.5481)
layout:setPercentWidth(0.0719)
layout:setPercentHeight(0.0643)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(204.9998)
layout:setRightMargin(389.0002)
layout:setTopMargin(300.1082)
layout:setBottomMargin(368.8918)
sp_target1:setBlendFunc({src = 1, dst = 771})
popup_bg_4:addChild(sp_target1)

--Create lb_target1
local lb_target1 = ccui.Text:create()
lb_target1:ignoreContentAdaptWithSize(true)
lb_target1:setTextAreaSize({width = 0, height = 0})
lb_target1:setFontSize(28)
lb_target1:setString([[目标说明]])
lb_target1:setTextVerticalAlignment(1)
lb_target1:enableShadow({r = 55, g = 168, b = 245, a = 255}, {width = 1, height = -1}, 0)
lb_target1:setLayoutComponentEnabled(true)
lb_target1:setName("lb_target1")
lb_target1:setTag(219)
lb_target1:setCascadeColorEnabled(true)
lb_target1:setCascadeOpacityEnabled(true)
lb_target1:setAnchorPoint(0.0000, 0.4910)
lb_target1:setPosition(260.2581, 390.3658)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_target1)
layout:setPositionPercentX(0.4067)
layout:setPositionPercentY(0.5460)
layout:setPercentWidth(0.1750)
layout:setPercentHeight(0.0392)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(260.2581)
layout:setRightMargin(267.7419)
layout:setTopMargin(310.3827)
layout:setBottomMargin(376.6173)
popup_bg_4:addChild(lb_target1)

--Create sp_target2
local sp_target2 = cc.Sprite:create("Default/Sprite.png")
sp_target2:setName("sp_target2")
sp_target2:setTag(216)
sp_target2:setCascadeColorEnabled(true)
sp_target2:setCascadeOpacityEnabled(true)
sp_target2:setPosition(227.9998, 337.0060)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_target2)
layout:setPositionPercentX(0.3562)
layout:setPositionPercentY(0.4713)
layout:setPercentWidth(0.0719)
layout:setPercentHeight(0.0643)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(204.9998)
layout:setRightMargin(389.0002)
layout:setTopMargin(354.9940)
layout:setBottomMargin(314.0060)
sp_target2:setBlendFunc({src = 1, dst = 771})
popup_bg_4:addChild(sp_target2)

--Create lb_target2
local lb_target2 = ccui.Text:create()
lb_target2:ignoreContentAdaptWithSize(true)
lb_target2:setTextAreaSize({width = 0, height = 0})
lb_target2:setFontSize(28)
lb_target2:setString([[目标说明]])
lb_target2:setTextVerticalAlignment(1)
lb_target2:enableShadow({r = 55, g = 168, b = 245, a = 255}, {width = 1, height = -1}, 0)
lb_target2:setLayoutComponentEnabled(true)
lb_target2:setName("lb_target2")
lb_target2:setTag(218)
lb_target2:setCascadeColorEnabled(true)
lb_target2:setCascadeOpacityEnabled(true)
lb_target2:setAnchorPoint(0.0000, 0.4518)
lb_target2:setPosition(260.2581, 335.2352)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_target2)
layout:setPositionPercentX(0.4067)
layout:setPositionPercentY(0.4689)
layout:setPercentWidth(0.1750)
layout:setPercentHeight(0.0392)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(260.2581)
layout:setRightMargin(267.7419)
layout:setTopMargin(364.4164)
layout:setBottomMargin(322.5836)
popup_bg_4:addChild(lb_target2)

--Create lb_tips
local lb_tips = ccui.Text:create()
lb_tips:ignoreContentAdaptWithSize(true)
lb_tips:setTextAreaSize({width = 0, height = 0})
lb_tips:setFontSize(22)
lb_tips:setString([[关卡Tips]])
lb_tips:setLayoutComponentEnabled(true)
lb_tips:setName("lb_tips")
lb_tips:setTag(220)
lb_tips:setCascadeColorEnabled(true)
lb_tips:setCascadeOpacityEnabled(true)
lb_tips:setPosition(323.7374, 225.8238)
lb_tips:setTextColor({r = 25, g = 80, b = 121})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_tips)
layout:setPositionPercentX(0.5058)
layout:setPositionPercentY(0.3158)
layout:setPercentWidth(0.1375)
layout:setPercentHeight(0.0308)
layout:setSize({width = 88.0000, height = 22.0000})
layout:setLeftMargin(279.7374)
layout:setRightMargin(272.2626)
layout:setTopMargin(478.1762)
layout:setBottomMargin(214.8238)
popup_bg_4:addChild(lb_tips)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("ui/tetris/power/close.png",0)
btn_close:loadTexturePressed("ui/tetris/power/close.png",0)
btn_close:loadTextureDisabled("ui/tetris/power/close.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 35, height = 43})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(279)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(558.2432, 667.4741)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8723)
layout:setPositionPercentY(0.9335)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0909)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(525.7432)
layout:setRightMargin(49.2568)
layout:setTopMargin(15.0259)
layout:setBottomMargin(634.9741)
popup_bg_4:addChild(btn_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

