--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create popup_bg_4
local popup_bg_4 = cc.Sprite:create("ui/tetris/power/popup_bg.png")
popup_bg_4:setName("popup_bg_4")
popup_bg_4:setTag(51)
popup_bg_4:setCascadeColorEnabled(true)
popup_bg_4:setCascadeOpacityEnabled(true)
popup_bg_4:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(popup_bg_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6294)
layout:setSize({width = 640.0000, height = 715.0000})
layout:setTopMargin(210.5000)
layout:setBottomMargin(210.5000)
popup_bg_4:setBlendFunc({src = 1, dst = 771})
Scene:addChild(popup_bg_4)

--Create game_pauseing_1
local game_pauseing_1 = cc.Sprite:create("ui/tetris/power/game_pauseing.png")
game_pauseing_1:setName("game_pauseing_1")
game_pauseing_1:setTag(76)
game_pauseing_1:setCascadeColorEnabled(true)
game_pauseing_1:setCascadeOpacityEnabled(true)
game_pauseing_1:setPosition(320.0000, 775.5509)
layout = ccui.LayoutComponent:bindLayoutComponent(game_pauseing_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6827)
layout:setPercentWidth(0.2813)
layout:setPercentHeight(0.0440)
layout:setSize({width = 180.0000, height = 50.0000})
layout:setLeftMargin(230.0000)
layout:setRightMargin(230.0000)
layout:setTopMargin(335.4491)
layout:setBottomMargin(750.5509)
game_pauseing_1:setBlendFunc({src = 1, dst = 771})
Scene:addChild(game_pauseing_1)

--Create btn_continue
local btn_continue = ccui.Button:create()
btn_continue:ignoreContentAdaptWithSize(false)
btn_continue:loadTextureNormal("ui/tetris/power/game_continue.png",0)
btn_continue:loadTexturePressed("ui/tetris/power/game_continue.png",0)
btn_continue:loadTextureDisabled("ui/tetris/power/game_continue.png",0)
btn_continue:setTitleFontSize(14)
btn_continue:setTitleColor({r = 65, g = 65, b = 70})
btn_continue:setScale9Enabled(true)
btn_continue:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_continue:setLayoutComponentEnabled(true)
btn_continue:setName("btn_continue")
btn_continue:setTag(80)
btn_continue:setCascadeColorEnabled(true)
btn_continue:setCascadeOpacityEnabled(true)
btn_continue:setPosition(320.0000, 665.7800)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_continue)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5861)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(427.2200)
layout:setBottomMargin(622.7800)
Scene:addChild(btn_continue)

--Create btn_vol
local btn_vol = ccui.Button:create()
btn_vol:ignoreContentAdaptWithSize(false)
btn_vol:loadTextureNormal("ui/tetris/power/vol_on.png",0)
btn_vol:loadTexturePressed("ui/tetris/power/vol_on.png",0)
btn_vol:loadTextureDisabled("ui/tetris/power/vol_on.png",0)
btn_vol:setTitleFontSize(14)
btn_vol:setTitleColor({r = 65, g = 65, b = 70})
btn_vol:setScale9Enabled(true)
btn_vol:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_vol:setLayoutComponentEnabled(true)
btn_vol:setName("btn_vol")
btn_vol:setTag(81)
btn_vol:setCascadeColorEnabled(true)
btn_vol:setCascadeOpacityEnabled(true)
btn_vol:setPosition(320.0000, 530.4500)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_vol)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4669)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(562.5500)
layout:setBottomMargin(487.4500)
Scene:addChild(btn_vol)

--Create btn_endgame
local btn_endgame = ccui.Button:create()
btn_endgame:ignoreContentAdaptWithSize(false)
btn_endgame:loadTextureNormal("ui/tetris/power/game_end.png",0)
btn_endgame:loadTexturePressed("ui/tetris/power/game_end.png",0)
btn_endgame:loadTextureDisabled("ui/tetris/power/game_end.png",0)
btn_endgame:setTitleFontSize(14)
btn_endgame:setTitleColor({r = 65, g = 65, b = 70})
btn_endgame:setScale9Enabled(true)
btn_endgame:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_endgame:setLayoutComponentEnabled(true)
btn_endgame:setName("btn_endgame")
btn_endgame:setTag(82)
btn_endgame:setCascadeColorEnabled(true)
btn_endgame:setCascadeOpacityEnabled(true)
btn_endgame:setPosition(320.0000, 394.2900)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_endgame)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3471)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(698.7100)
layout:setBottomMargin(351.2900)
Scene:addChild(btn_endgame)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

