--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create scroll_view
local scroll_view = ccui.ScrollView:create()
scroll_view:setBounceEnabled(true)
scroll_view:setInnerContainerSize({width = 400, height = 602})
scroll_view:ignoreContentAdaptWithSize(false)
scroll_view:setClippingEnabled(true)
scroll_view:setBackGroundColorType(1)
scroll_view:setBackGroundColor({r = 255, g = 150, b = 100})
scroll_view:setBackGroundColorOpacity(102)
scroll_view:setLayoutComponentEnabled(true)
scroll_view:setName("scroll_view")
scroll_view:setTag(19)
scroll_view:setCascadeColorEnabled(true)
scroll_view:setCascadeOpacityEnabled(true)
scroll_view:setPosition(305.8662, 135.9395)
layout = ccui.LayoutComponent:bindLayoutComponent(scroll_view)
layout:setPositionPercentX(0.3186)
layout:setPositionPercentY(0.2124)
layout:setPercentWidth(0.4167)
layout:setPercentHeight(0.6250)
layout:setSize({width = 400.0000, height = 400.0000})
layout:setLeftMargin(305.8662)
layout:setRightMargin(254.1338)
layout:setTopMargin(104.0605)
layout:setBottomMargin(135.9395)
Scene:addChild(scroll_view)

--Create scroll_text
local scroll_text = ccui.Text:create()
scroll_text:ignoreContentAdaptWithSize(true)
scroll_text:setTextAreaSize({width = 0, height = 0})
scroll_text:setFontSize(20)
scroll_text:setString([[Text Label]])
scroll_text:setLayoutComponentEnabled(true)
scroll_text:setName("scroll_text")
scroll_text:setTag(20)
scroll_text:setCascadeColorEnabled(true)
scroll_text:setCascadeOpacityEnabled(true)
scroll_text:setPosition(116.8199, 373.8226)
layout = ccui.LayoutComponent:bindLayoutComponent(scroll_text)
layout:setPositionPercentX(0.1217)
layout:setPositionPercentY(0.5841)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.0313)
layout:setSize({width = 100.0000, height = 20.0000})
layout:setLeftMargin(66.8199)
layout:setRightMargin(793.1802)
layout:setTopMargin(256.1774)
layout:setBottomMargin(363.8226)
Scene:addChild(scroll_text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

