--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create user_name
local user_name = ccui.Text:create()
user_name:ignoreContentAdaptWithSize(true)
user_name:setTextAreaSize({width = 0, height = 0})
user_name:setFontSize(32)
user_name:setString([[${user.fullName}]])
user_name:setLayoutComponentEnabled(true)
user_name:setName("user_name")
user_name:setTag(10)
user_name:setCascadeColorEnabled(true)
user_name:setCascadeOpacityEnabled(true)
user_name:setPosition(326.0740, 586.5518)
layout = ccui.LayoutComponent:bindLayoutComponent(user_name)
layout:setPositionPercentX(0.5095)
layout:setPositionPercentY(0.5163)
layout:setPercentWidth(0.3672)
layout:setPercentHeight(0.0326)
layout:setSize({width = 235.0000, height = 37.0000})
layout:setLeftMargin(208.5740)
layout:setRightMargin(196.4260)
layout:setTopMargin(530.9482)
layout:setBottomMargin(568.0518)
Scene:addChild(user_name)

--Create bg_input
local bg_input = ccui.ImageView:create()
bg_input:ignoreContentAdaptWithSize(false)
bg_input:loadTexture("res/input_bg.png",0)
bg_input:setScale9Enabled(true)
bg_input:setCapInsets({x = 5, y = 5, width = 21, height = 21})
bg_input:setTouchEnabled(true);
bg_input:setLayoutComponentEnabled(true)
bg_input:setName("bg_input")
bg_input:setTag(54)
bg_input:setCascadeColorEnabled(true)
bg_input:setCascadeOpacityEnabled(true)
bg_input:setPosition(318.4714, 211.5788)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_input)
layout:setPositionPercentX(0.4976)
layout:setPositionPercentY(0.1862)
layout:setPercentWidth(0.5469)
layout:setPercentHeight(0.0616)
layout:setSize({width = 350.0000, height = 70.0000})
layout:setLeftMargin(143.4714)
layout:setRightMargin(146.5286)
layout:setTopMargin(889.4213)
layout:setBottomMargin(176.5788)
Scene:addChild(bg_input)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

