--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(85)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3313)
layout:setPercentHeight(0.2465)
layout:setSize({width = 852.0000, height = 280.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
layout:setTopMargin(996.0000)
layout:setBottomMargin(-140.0000)
Scene:addChild(panel)

--Create intro_bg
local intro_bg = cc.Sprite:create("ui/pvp/pvp_start_bg.png")
intro_bg:setName("intro_bg")
intro_bg:setTag(170)
intro_bg:setCascadeColorEnabled(true)
intro_bg:setCascadeOpacityEnabled(true)
intro_bg:setPosition(426.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(intro_bg)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.9643)
layout:setSize({width = 850.0000, height = 200.0000})
layout:setTopMargin(145.0000)
layout:setBottomMargin(-135.0000)
intro_bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(intro_bg)

--Create lb_self
local lb_self = ccui.Text:create()
lb_self:ignoreContentAdaptWithSize(true)
lb_self:setTextAreaSize({width = 0, height = 0})
lb_self:setFontSize(38)
lb_self:setString([[收集星星]])
lb_self:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 2, height = -1}, 0)
lb_self:setLayoutComponentEnabled(true)
lb_self:setName("lb_self")
lb_self:setTag(171)
lb_self:setCascadeColorEnabled(true)
lb_self:setCascadeOpacityEnabled(true)
lb_self:setPosition(212.5360, 0.0000)
lb_self:setTextColor({r = 104, g = 178, b = 246})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_self)
layout:setPositionPercentX(0.2495)
layout:setPercentWidth(0.1784)
layout:setPercentHeight(0.1357)
layout:setSize({width = 152.0000, height = 38.0000})
layout:setLeftMargin(136.5360)
layout:setRightMargin(563.4640)
layout:setTopMargin(261.0000)
layout:setBottomMargin(-19.0000)
panel:addChild(lb_self)

--Create lb_target
local lb_target = ccui.Text:create()
lb_target:ignoreContentAdaptWithSize(true)
lb_target:setTextAreaSize({width = 0, height = 0})
lb_target:setFontSize(38)
lb_target:setString([[收集星星]])
lb_target:enableShadow({r = 11, g = 29, b = 26, a = 255}, {width = 2, height = -1}, 0)
lb_target:setLayoutComponentEnabled(true)
lb_target:setName("lb_target")
lb_target:setTag(9)
lb_target:setCascadeColorEnabled(true)
lb_target:setCascadeOpacityEnabled(true)
lb_target:setPosition(639.0417, 0.0000)
lb_target:setTextColor({r = 242, g = 102, b = 139})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_target)
layout:setPositionPercentX(0.7500)
layout:setPercentWidth(0.1784)
layout:setPercentHeight(0.1357)
layout:setSize({width = 152.0000, height = 38.0000})
layout:setLeftMargin(563.0417)
layout:setRightMargin(136.9583)
layout:setTopMargin(261.0000)
layout:setBottomMargin(-19.0000)
panel:addChild(lb_target)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

