--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 567.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
layout:setTopMargin(0.0002)
layout:setBottomMargin(-0.0002)
Scene:addChild(panel)

--Create pvp_bg
local pvp_bg = cc.Sprite:create("ui/tetris/power/pvp_bg.png")
pvp_bg:setName("pvp_bg")
pvp_bg:setTag(138)
pvp_bg:setCascadeColorEnabled(true)
pvp_bg:setCascadeOpacityEnabled(true)
pvp_bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(pvp_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3281)
layout:setPercentHeight(1.0000)
layout:setSize({width = 850.0000, height = 1136.0000})
layout:setLeftMargin(-105.0000)
layout:setRightMargin(-105.0000)
pvp_bg:setBlendFunc({src = 770, dst = 771})
panel:addChild(pvp_bg)

--Create building_bg
local building_bg = cc.Sprite:create("ui/tetris/power/building_bg.png")
building_bg:setName("building_bg")
building_bg:setTag(139)
building_bg:setCascadeColorEnabled(true)
building_bg:setCascadeOpacityEnabled(true)
building_bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(building_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6563)
layout:setPercentHeight(0.3257)
layout:setSize({width = 420.0000, height = 370.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(110.0000)
layout:setTopMargin(383.0000)
layout:setBottomMargin(383.0000)
building_bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(building_bg)

--Create btn_pvp
local btn_pvp = ccui.Button:create()
btn_pvp:ignoreContentAdaptWithSize(false)
btn_pvp:loadTextureNormal("ui/tetris/power/btn_pvp.png",0)
btn_pvp:loadTexturePressed("ui/tetris/power/btn_pvp.png",0)
btn_pvp:loadTextureDisabled("ui/tetris/power/btn_pvp.png",0)
btn_pvp:setTitleFontSize(14)
btn_pvp:setTitleColor({r = 65, g = 65, b = 70})
btn_pvp:setScale9Enabled(true)
btn_pvp:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_pvp:setLayoutComponentEnabled(true)
btn_pvp:setName("btn_pvp")
btn_pvp:setTag(140)
btn_pvp:setCascadeColorEnabled(true)
btn_pvp:setCascadeOpacityEnabled(true)
btn_pvp:setPosition(320.0000, 336.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_pvp)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2958)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(757.0000)
layout:setBottomMargin(293.0000)
panel:addChild(btn_pvp)

--Create btn_cancel
local btn_cancel = ccui.Button:create()
btn_cancel:ignoreContentAdaptWithSize(false)
btn_cancel:loadTextureNormal("ui/tetris/power/btn_cancel.png",0)
btn_cancel:loadTexturePressed("ui/tetris/power/btn_cancel.png",0)
btn_cancel:loadTextureDisabled("ui/tetris/power/btn_cancel.png",0)
btn_cancel:setTitleFontSize(14)
btn_cancel:setTitleColor({r = 65, g = 65, b = 70})
btn_cancel:setScale9Enabled(true)
btn_cancel:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_cancel:setLayoutComponentEnabled(true)
btn_cancel:setName("btn_cancel")
btn_cancel:setTag(145)
btn_cancel:setCascadeColorEnabled(true)
btn_cancel:setCascadeOpacityEnabled(true)
btn_cancel:setVisible(false)
btn_cancel:setPosition(320.0000, 336.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_cancel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2958)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(757.0000)
layout:setBottomMargin(293.0000)
panel:addChild(btn_cancel)

--Create search_panel
local search_panel = ccui.Layout:create()
search_panel:ignoreContentAdaptWithSize(false)
search_panel:setClippingEnabled(false)
search_panel:setBackGroundColorOpacity(102)
search_panel:setTouchEnabled(true);
search_panel:setLayoutComponentEnabled(true)
search_panel:setName("search_panel")
search_panel:setTag(144)
search_panel:setCascadeColorEnabled(true)
search_panel:setCascadeOpacityEnabled(true)
search_panel:setVisible(false)
search_panel:setAnchorPoint(0.5000, 0.5000)
search_panel:setPosition(320.0000, 864.5298)
layout = ccui.LayoutComponent:bindLayoutComponent(search_panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7610)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.0880)
layout:setSize({width = 200.0000, height = 100.0000})
layout:setLeftMargin(220.0000)
layout:setRightMargin(220.0000)
layout:setTopMargin(221.4702)
layout:setBottomMargin(814.5298)
panel:addChild(search_panel)

--Create btn_matchbg
local btn_matchbg = cc.Sprite:create("ui/tetris/power/btn_matchbg.png")
btn_matchbg:setName("btn_matchbg")
btn_matchbg:setTag(142)
btn_matchbg:setCascadeColorEnabled(true)
btn_matchbg:setCascadeOpacityEnabled(true)
btn_matchbg:setPosition(99.3266, 13.3734)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_matchbg)
layout:setPositionPercentX(0.4966)
layout:setPositionPercentY(0.1337)
layout:setPercentWidth(1.8750)
layout:setPercentHeight(0.5000)
layout:setSize({width = 375.0000, height = 50.0000})
layout:setLeftMargin(-88.1734)
layout:setRightMargin(-86.8266)
layout:setTopMargin(61.6266)
layout:setBottomMargin(-11.6266)
btn_matchbg:setBlendFunc({src = 1, dst = 771})
search_panel:addChild(btn_matchbg)

--Create btn_search
local btn_search = cc.Sprite:create("ui/tetris/power/btn_search.png")
btn_search:setName("btn_search")
btn_search:setTag(141)
btn_search:setCascadeColorEnabled(true)
btn_search:setCascadeOpacityEnabled(true)
btn_search:setPosition(-40.7681, 3.0705)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_search)
layout:setPositionPercentX(-0.2038)
layout:setPositionPercentY(0.0307)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.7000)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(-75.7681)
layout:setRightMargin(205.7681)
layout:setTopMargin(61.9295)
layout:setBottomMargin(-31.9295)
btn_search:setBlendFunc({src = 1, dst = 771})
search_panel:addChild(btn_search)

--Create lb_searchtext
local lb_searchtext = ccui.Text:create()
lb_searchtext:ignoreContentAdaptWithSize(true)
lb_searchtext:setTextAreaSize({width = 0, height = 0})
lb_searchtext:setFontSize(24)
lb_searchtext:setString([[正在为您匹配对手...]])
lb_searchtext:enableShadow({r = 106, g = 171, b = 235, a = 255}, {width = 1, height = -1}, 0)
lb_searchtext:setLayoutComponentEnabled(true)
lb_searchtext:setName("lb_searchtext")
lb_searchtext:setTag(143)
lb_searchtext:setCascadeColorEnabled(true)
lb_searchtext:setCascadeOpacityEnabled(true)
lb_searchtext:setPosition(99.3294, 13.0694)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_searchtext)
layout:setPositionPercentX(0.4966)
layout:setPositionPercentY(0.1307)
layout:setPercentWidth(1.1400)
layout:setPercentHeight(0.2400)
layout:setSize({width = 228.0000, height = 24.0000})
layout:setLeftMargin(-14.6706)
layout:setRightMargin(-13.3294)
layout:setTopMargin(74.9306)
layout:setBottomMargin(1.0694)
search_panel:addChild(lb_searchtext)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

