--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create bg
local bg = cc.Sprite:create("ui/shop/shop_bg.png")
bg:setName("bg")
bg:setTag(77)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9766)
layout:setPercentHeight(0.7658)
layout:setSize({width = 625.0000, height = 870.0000})
layout:setLeftMargin(7.5000)
layout:setRightMargin(7.5000)
layout:setTopMargin(133.0000)
layout:setBottomMargin(133.0000)
bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(bg)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureNormal("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTexturePressed("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureDisabled("close.png",1)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 35, height = 43})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(82)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(550.8793, 955.0356)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8607)
layout:setPositionPercentY(0.8407)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0572)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(518.3793)
layout:setRightMargin(56.6207)
layout:setTopMargin(148.4644)
layout:setBottomMargin(922.5356)
panel:addChild(btn_close)

--Create lb_title
local lb_title = ccui.Text:create()
lb_title:ignoreContentAdaptWithSize(true)
lb_title:setTextAreaSize({width = 0, height = 0})
lb_title:setFontSize(28)
lb_title:setString([[购买钻石]])
lb_title:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 1, height = -1}, 0)
lb_title:setLayoutComponentEnabled(true)
lb_title:setName("lb_title")
lb_title:setTag(138)
lb_title:setCascadeColorEnabled(true)
lb_title:setCascadeOpacityEnabled(true)
lb_title:setPosition(319.9977, 959.5456)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8447)
layout:setPercentWidth(0.1750)
layout:setPercentHeight(0.0246)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(263.9977)
layout:setRightMargin(264.0023)
layout:setTopMargin(162.4544)
layout:setBottomMargin(945.5456)
panel:addChild(lb_title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

