--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(330.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5156)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0313)
layout:setPercentHeight(0.0968)
layout:setSize({width = 660.0000, height = 110.0000})
layout:setRightMargin(-20.0000)
layout:setTopMargin(513.0000)
layout:setBottomMargin(513.0000)
Scene:addChild(panel)

--Create bg
local bg = cc.Sprite:create("ui/rank/rank_line_bg.png")
bg:setName("bg")
bg:setTag(95)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(325.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.4924)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 660.0000, height = 110.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(5.0000)
bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(bg)

--Create lb_point
local lb_point = ccui.Text:create()
lb_point:ignoreContentAdaptWithSize(true)
lb_point:setTextAreaSize({width = 0, height = 0})
lb_point:setFontSize(28)
lb_point:setString([[1234]])
lb_point:enableShadow({r = 64, g = 57, b = 53, a = 255}, {width = 1, height = -1}, 0)
lb_point:setLayoutComponentEnabled(true)
lb_point:setName("lb_point")
lb_point:setTag(186)
lb_point:setCascadeColorEnabled(true)
lb_point:setCascadeOpacityEnabled(true)
lb_point:setAnchorPoint(0.0000, 0.5000)
lb_point:setPosition(498.3600, 55.0000)
lb_point:setTextColor({r = 253, g = 244, b = 2})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_point)
layout:setPositionPercentX(0.7551)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0848)
layout:setPercentHeight(0.2545)
layout:setSize({width = 56.0000, height = 28.0000})
layout:setLeftMargin(498.3600)
layout:setRightMargin(105.6400)
layout:setTopMargin(41.0000)
layout:setBottomMargin(41.0000)
panel:addChild(lb_point)

--Create sp_point
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
local sp_point = cc.Sprite:createWithSpriteFrameName("score_bg.png")
sp_point:setName("sp_point")
sp_point:setTag(98)
sp_point:setCascadeColorEnabled(true)
sp_point:setCascadeOpacityEnabled(true)
sp_point:setPosition(474.0678, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_point)
layout:setPositionPercentX(0.7183)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0667)
layout:setPercentHeight(0.3273)
layout:setSize({width = 44.0000, height = 36.0000})
layout:setLeftMargin(452.0678)
layout:setRightMargin(163.9322)
layout:setTopMargin(37.0000)
layout:setBottomMargin(37.0000)
sp_point:setBlendFunc({src = 1, dst = 771})
panel:addChild(sp_point)

--Create lb_name
local lb_name = ccui.Text:create()
lb_name:ignoreContentAdaptWithSize(true)
lb_name:setTextAreaSize({width = 0, height = 0})
lb_name:setFontSize(32)
lb_name:setString([[玩家名字七个字]])
lb_name:enableShadow({r = 64, g = 57, b = 53, a = 255}, {width = 2, height = -2}, 0)
lb_name:setLayoutComponentEnabled(true)
lb_name:setName("lb_name")
lb_name:setTag(97)
lb_name:setCascadeColorEnabled(true)
lb_name:setCascadeOpacityEnabled(true)
lb_name:setPosition(235.3890, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_name)
layout:setPositionPercentX(0.3567)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3394)
layout:setPercentHeight(0.3000)
layout:setSize({width = 224.0000, height = 33.0000})
layout:setLeftMargin(123.3890)
layout:setRightMargin(312.6110)
layout:setTopMargin(38.5000)
layout:setBottomMargin(38.5000)
panel:addChild(lb_name)

--Create sp_cup
local sp_cup = cc.Sprite:create("ui/rank/icon_gold_cup.png")
sp_cup:setName("sp_cup")
sp_cup:setTag(96)
sp_cup:setCascadeColorEnabled(true)
sp_cup:setCascadeOpacityEnabled(true)
sp_cup:setPosition(54.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_cup)
layout:setPositionPercentX(0.0818)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1152)
layout:setPercentHeight(0.6545)
layout:setSize({width = 76.0000, height = 72.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(568.0000)
layout:setTopMargin(19.0000)
layout:setBottomMargin(19.0000)
sp_cup:setBlendFunc({src = 1, dst = 771})
panel:addChild(sp_cup)

--Create lb_rank
local lb_rank = ccui.TextAtlas:create([[100]],
													"ui/number_atlas/rank.png",
													30,
													40,
													"0")
lb_rank:setLayoutComponentEnabled(true)
lb_rank:setName("lb_rank")
lb_rank:setTag(104)
lb_rank:setCascadeColorEnabled(true)
lb_rank:setCascadeOpacityEnabled(true)
lb_rank:setVisible(false)
lb_rank:setPosition(54.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_rank)
layout:setPositionPercentX(0.0818)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1364)
layout:setPercentHeight(0.3636)
layout:setSize({width = 90.0000, height = 40.0000})
layout:setLeftMargin(9.0000)
layout:setRightMargin(561.0000)
layout:setTopMargin(35.0000)
layout:setBottomMargin(35.0000)
panel:addChild(lb_rank)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

