--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create layer_bg
local layer_bg = cc.Sprite:create("ui/bg/pvp_bg.png")
layer_bg:setName("layer_bg")
layer_bg:setTag(51)
layer_bg:setCascadeColorEnabled(true)
layer_bg:setCascadeOpacityEnabled(true)
layer_bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(layer_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3281)
layout:setPercentHeight(1.0000)
layout:setSize({width = 850.0000, height = 1136.0000})
layout:setLeftMargin(-105.0000)
layout:setRightMargin(-105.0000)
layer_bg:setBlendFunc({src = 770, dst = 771})
panel:addChild(layer_bg)

--Create bg
local bg = cc.Sprite:create("ui/rank/rank_bg.png")
bg:setName("bg")
bg:setTag(89)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(320.0000, 568.0000)
bg:setScaleX(0.9000)
bg:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3313)
layout:setPercentHeight(0.9155)
layout:setSize({width = 852.0000, height = 1040.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
layout:setTopMargin(48.0000)
layout:setBottomMargin(48.0000)
bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(bg)

--Create list_view
local list_view = ccui.ListView:create()
list_view:setItemsMargin(2)
list_view:setDirection(1)
list_view:setGravity(2)
list_view:ignoreContentAdaptWithSize(false)
list_view:setClippingEnabled(true)
list_view:setBackGroundColorOpacity(102)
list_view:setLayoutComponentEnabled(true)
list_view:setName("list_view")
list_view:setTag(90)
list_view:setCascadeColorEnabled(true)
list_view:setCascadeOpacityEnabled(true)
list_view:setAnchorPoint(0.5000, 0.5000)
list_view:setPosition(320.0003, 446.0033)
layout = ccui.LayoutComponent:bindLayoutComponent(list_view)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3926)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.5634)
layout:setSize({width = 640.0000, height = 640.0000})
layout:setLeftMargin(0.0003)
layout:setRightMargin(-0.0003)
layout:setTopMargin(369.9967)
layout:setBottomMargin(126.0033)
panel:addChild(list_view)

--Create sp_self
local sp_self = cc.Sprite:create("ui/rank/rank_self_bg.png")
sp_self:setName("sp_self")
sp_self:setTag(91)
sp_self:setCascadeColorEnabled(true)
sp_self:setCascadeOpacityEnabled(true)
sp_self:setPosition(320.0001, 823.0000)
sp_self:setScaleX(0.9000)
sp_self:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_self)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7245)
layout:setPercentWidth(1.0234)
layout:setPercentHeight(0.1012)
layout:setSize({width = 655.0000, height = 115.0000})
layout:setLeftMargin(-7.4999)
layout:setRightMargin(-7.5001)
layout:setTopMargin(255.5000)
layout:setBottomMargin(765.5000)
sp_self:setBlendFunc({src = 1, dst = 771})
panel:addChild(sp_self)

--Create lb_ranktitle
local lb_ranktitle = ccui.Text:create()
lb_ranktitle:ignoreContentAdaptWithSize(true)
lb_ranktitle:setTextAreaSize({width = 0, height = 0})
lb_ranktitle:setFontSize(32)
lb_ranktitle:setString([[我的排名：]])
lb_ranktitle:enableShadow({r = 64, g = 57, b = 53, a = 255}, {width = 1, height = -1}, 0)
lb_ranktitle:setLayoutComponentEnabled(true)
lb_ranktitle:setName("lb_ranktitle")
lb_ranktitle:setTag(92)
lb_ranktitle:setCascadeColorEnabled(true)
lb_ranktitle:setCascadeOpacityEnabled(true)
lb_ranktitle:setAnchorPoint(0.0000, 0.5000)
lb_ranktitle:setPosition(39.5654, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_ranktitle)
layout:setPositionPercentX(0.0604)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(0.2443)
layout:setPercentHeight(0.2870)
layout:setSize({width = 160.0000, height = 33.0000})
layout:setLeftMargin(39.5654)
layout:setRightMargin(455.4346)
layout:setTopMargin(38.5000)
layout:setBottomMargin(43.5000)
sp_self:addChild(lb_ranktitle)

--Create lb_myrank
local lb_myrank = ccui.Text:create()
lb_myrank:ignoreContentAdaptWithSize(true)
lb_myrank:setTextAreaSize({width = 0, height = 0})
lb_myrank:setFontSize(32)
lb_myrank:setString([[123]])
lb_myrank:enableShadow({r = 64, g = 57, b = 53, a = 255}, {width = 1, height = -1}, 0)
lb_myrank:setLayoutComponentEnabled(true)
lb_myrank:setName("lb_myrank")
lb_myrank:setTag(187)
lb_myrank:setCascadeColorEnabled(true)
lb_myrank:setCascadeOpacityEnabled(true)
lb_myrank:setAnchorPoint(0.0000, 0.5000)
lb_myrank:setPosition(197.9945, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_myrank)
layout:setPositionPercentX(0.3023)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(0.0733)
layout:setPercentHeight(0.2870)
layout:setSize({width = 48.0000, height = 33.0000})
layout:setLeftMargin(197.9945)
layout:setRightMargin(409.0055)
layout:setTopMargin(38.5000)
layout:setBottomMargin(43.5000)
sp_self:addChild(lb_myrank)

--Create btn_recv
local btn_recv = ccui.Button:create()
btn_recv:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_recv:loadTextureNormal("btn_recv.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_recv:loadTexturePressed("btn_recv.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_recv:loadTextureDisabled("btn_recv.png",1)
btn_recv:setTitleFontSize(14)
btn_recv:setTitleColor({r = 65, g = 65, b = 70})
btn_recv:setScale9Enabled(true)
btn_recv:setCapInsets({x = 15, y = 11, width = 140, height = 38})
btn_recv:setLayoutComponentEnabled(true)
btn_recv:setName("btn_recv")
btn_recv:setTag(93)
btn_recv:setCascadeColorEnabled(true)
btn_recv:setCascadeOpacityEnabled(true)
btn_recv:setPosition(513.7226, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_recv)
layout:setPositionPercentX(0.7843)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(0.2595)
layout:setPercentHeight(0.5217)
layout:setSize({width = 170.0000, height = 60.0000})
layout:setLeftMargin(428.7226)
layout:setRightMargin(56.2774)
layout:setTopMargin(25.0000)
layout:setBottomMargin(30.0000)
sp_self:addChild(btn_recv)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

