--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(85)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(0.0880)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(590.0000)
layout:setTopMargin(1086.0000)
layout:setBottomMargin(-50.0000)
Scene:addChild(panel)

--Create btn
local btn = ccui.Button:create()
btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/main.plist")
btn:loadTextureNormal("power_clearstone_open.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/main.plist")
btn:loadTexturePressed("power_clearstone_open.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/main.plist")
btn:loadTextureDisabled("power_clearstone_unopen.png",1)
btn:setTitleFontSize(14)
btn:setTitleColor({r = 65, g = 65, b = 70})
btn:setScale9Enabled(true)
btn:setCapInsets({x = 15, y = 11, width = 60, height = 68})
btn:setLayoutComponentEnabled(true)
btn:setName("btn")
btn:setTag(81)
btn:setCascadeColorEnabled(true)
btn:setCascadeOpacityEnabled(true)
btn:setAnchorPoint(0.3000, 0.5000)
btn:setPosition(32.2294, 63.0181)
layout = ccui.LayoutComponent:bindLayoutComponent(btn)
layout:setPositionPercentX(0.3223)
layout:setPositionPercentY(0.6302)
layout:setPercentWidth(0.9000)
layout:setPercentHeight(0.9000)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(5.2294)
layout:setRightMargin(4.7706)
layout:setTopMargin(-8.0181)
layout:setBottomMargin(18.0181)
panel:addChild(btn)

--Create star1
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
local star1 = cc.Sprite:createWithSpriteFrameName("power_star.png")
star1:setName("star1")
star1:setTag(82)
star1:setCascadeColorEnabled(true)
star1:setCascadeOpacityEnabled(true)
star1:setVisible(false)
star1:setAnchorPoint(0.3000, 0.5000)
star1:setPosition(41.4574, 15.2997)
star1:setScaleX(0.8000)
star1:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(star1)
layout:setPositionPercentX(0.4146)
layout:setPositionPercentY(0.1530)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.3500)
layout:setSize({width = 35.0000, height = 35.0000})
layout:setLeftMargin(30.9574)
layout:setRightMargin(34.0426)
layout:setTopMargin(67.2003)
layout:setBottomMargin(-2.2003)
star1:setBlendFunc({src = 1, dst = 771})
panel:addChild(star1)

--Create star3
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
local star3 = cc.Sprite:createWithSpriteFrameName("power_star.png")
star3:setName("star3")
star3:setTag(83)
star3:setCascadeColorEnabled(true)
star3:setCascadeOpacityEnabled(true)
star3:setVisible(false)
star3:setAnchorPoint(0.3000, 0.5000)
star3:setPosition(70.7408, 21.1345)
star3:setScaleX(0.6400)
star3:setScaleY(0.6400)
layout = ccui.LayoutComponent:bindLayoutComponent(star3)
layout:setPositionPercentX(0.7074)
layout:setPositionPercentY(0.2113)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.3500)
layout:setSize({width = 35.0000, height = 35.0000})
layout:setLeftMargin(60.2408)
layout:setRightMargin(4.7592)
layout:setTopMargin(61.3655)
layout:setBottomMargin(3.6345)
star3:setBlendFunc({src = 1, dst = 771})
panel:addChild(star3)

--Create star2
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
local star2 = cc.Sprite:createWithSpriteFrameName("power_star.png")
star2:setName("star2")
star2:setTag(84)
star2:setCascadeColorEnabled(true)
star2:setCascadeOpacityEnabled(true)
star2:setVisible(false)
star2:setAnchorPoint(0.3000, 0.5000)
star2:setPosition(14.8655, 21.7497)
star2:setScaleX(0.6400)
star2:setScaleY(0.6400)
layout = ccui.LayoutComponent:bindLayoutComponent(star2)
layout:setPositionPercentX(0.1487)
layout:setPositionPercentY(0.2175)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.3500)
layout:setSize({width = 35.0000, height = 35.0000})
layout:setLeftMargin(4.3655)
layout:setRightMargin(60.6345)
layout:setTopMargin(60.7503)
layout:setBottomMargin(4.2497)
star2:setBlendFunc({src = 1, dst = 771})
panel:addChild(star2)

--Create lb_armynum
local lb_armynum = ccui.TextAtlas:create([[12]],
													"ui/number_atlas/army_num_out.png",
													16,
													25,
													"0")
lb_armynum:setLayoutComponentEnabled(true)
lb_armynum:setName("lb_armynum")
lb_armynum:setTag(157)
lb_armynum:setCascadeColorEnabled(true)
lb_armynum:setCascadeOpacityEnabled(true)
lb_armynum:setPosition(47.2547, 27.7238)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_armynum)
layout:setPositionPercentX(0.4725)
layout:setPositionPercentY(0.2772)
layout:setPercentWidth(0.3200)
layout:setPercentHeight(0.2500)
layout:setSize({width = 32.0000, height = 25.0000})
layout:setLeftMargin(31.2547)
layout:setRightMargin(36.7453)
layout:setTopMargin(59.7762)
layout:setBottomMargin(15.2238)
panel:addChild(lb_armynum)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

