--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create bg
local bg = cc.Sprite:create("ui/bg/intro_bg.png")
bg:setName("bg")
bg:setTag(77)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3313)
layout:setPercentHeight(0.2377)
layout:setSize({width = 852.0000, height = 270.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
layout:setTopMargin(433.0000)
layout:setBottomMargin(433.0000)
bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(bg)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureNormal("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTexturePressed("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureDisabled("close.png",1)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 35, height = 43})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(82)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(618.5406, 612.1099)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9665)
layout:setPositionPercentY(0.5388)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0572)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(586.0406)
layout:setRightMargin(-11.0407)
layout:setTopMargin(491.3901)
layout:setBottomMargin(579.6099)
panel:addChild(btn_close)

--Create lb_info
local lb_info = ccui.Text:create()
lb_info:ignoreContentAdaptWithSize(true)
lb_info:setTextAreaSize({width = 0, height = 0})
lb_info:setFontSize(32)
lb_info:setString([[延长关卡时间：15秒！]])
lb_info:enableShadow({r = 26, g = 26, b = 26, a = 255}, {width = 1, height = -1}, 0)
lb_info:setLayoutComponentEnabled(true)
lb_info:setName("lb_info")
lb_info:setTag(83)
lb_info:setCascadeColorEnabled(true)
lb_info:setCascadeOpacityEnabled(true)
lb_info:setPosition(320.0000, 572.8559)
lb_info:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_info)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5043)
layout:setPercentWidth(0.5000)
layout:setPercentHeight(0.0290)
layout:setSize({width = 320.0000, height = 33.0000})
layout:setLeftMargin(160.0000)
layout:setRightMargin(160.0000)
layout:setTopMargin(546.6441)
layout:setBottomMargin(556.3559)
panel:addChild(lb_info)

--Create btn_buy
local btn_buy = ccui.Button:create()
btn_buy:ignoreContentAdaptWithSize(false)
btn_buy:loadTextureNormal("ui/tips/btn_buy_time.png",0)
btn_buy:loadTexturePressed("ui/tips/btn_buy_time.png",0)
btn_buy:loadTextureDisabled("ui/tips/btn_buy_time.png",0)
btn_buy:setTitleFontSize(14)
btn_buy:setTitleColor({r = 65, g = 65, b = 70})
btn_buy:setScale9Enabled(true)
btn_buy:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_buy:setLayoutComponentEnabled(true)
btn_buy:setName("btn_buy")
btn_buy:setTag(79)
btn_buy:setCascadeColorEnabled(true)
btn_buy:setCascadeOpacityEnabled(true)
btn_buy:setPosition(320.0000, 502.8500)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_buy)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4426)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0000)
layout:setRightMargin(174.0000)
layout:setTopMargin(590.1500)
layout:setBottomMargin(459.8500)
panel:addChild(btn_buy)

--Create lb_price
local lb_price = ccui.Text:create()
lb_price:ignoreContentAdaptWithSize(true)
lb_price:setTextAreaSize({width = 0, height = 0})
lb_price:setFontSize(28)
lb_price:setString([[5]])
lb_price:setLayoutComponentEnabled(true)
lb_price:setName("lb_price")
lb_price:setTag(153)
lb_price:setCascadeColorEnabled(true)
lb_price:setCascadeOpacityEnabled(true)
lb_price:setAnchorPoint(0.0000, 0.5000)
lb_price:setPosition(250.0958, 502.8500)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_price)
layout:setPositionPercentX(0.3908)
layout:setPositionPercentY(0.4426)
layout:setPercentWidth(0.0219)
layout:setPercentHeight(0.0246)
layout:setSize({width = 14.0000, height = 28.0000})
layout:setLeftMargin(250.0958)
layout:setRightMargin(375.9042)
layout:setTopMargin(619.1500)
layout:setBottomMargin(488.8500)
panel:addChild(lb_price)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

