--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create bar_bg
local bar_bg = ccui.ImageView:create()
bar_bg:ignoreContentAdaptWithSize(false)
bar_bg:loadTexture("ui/tetris/power/main_bar_bg.png",0)
bar_bg:setScale9Enabled(true)
bar_bg:setCapInsets({x = 50, y = 0, width = 50, height = 96})
bar_bg:setLayoutComponentEnabled(true)
bar_bg:setName("bar_bg")
bar_bg:setTag(603)
bar_bg:setCascadeColorEnabled(true)
bar_bg:setCascadeOpacityEnabled(true)
bar_bg:setPosition(318.6424, 1093.9990)
layout = ccui.LayoutComponent:bindLayoutComponent(bar_bg)
layout:setPositionPercentX(0.4979)
layout:setPositionPercentY(0.9630)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0845)
layout:setSize({width = 640.0000, height = 96.0000})
layout:setLeftMargin(-1.3576)
layout:setRightMargin(1.3575)
layout:setTopMargin(-5.9991)
layout:setBottomMargin(1045.9990)
panel:addChild(bar_bg)

--Create energy_bg_3
local energy_bg_3 = cc.Sprite:create("ui/tetris/power/energy_bg.png")
energy_bg_3:setName("energy_bg_3")
energy_bg_3:setTag(605)
energy_bg_3:setCascadeColorEnabled(true)
energy_bg_3:setCascadeOpacityEnabled(true)
energy_bg_3:setPosition(140.0222, 1093.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(energy_bg_3)
layout:setPositionPercentX(0.2188)
layout:setPositionPercentY(0.9621)
layout:setPercentWidth(0.3688)
layout:setPercentHeight(0.0528)
layout:setSize({width = 236.0000, height = 60.0000})
layout:setLeftMargin(22.0222)
layout:setRightMargin(381.9778)
layout:setTopMargin(13.0000)
layout:setBottomMargin(1063.0000)
energy_bg_3:setBlendFunc({src = 1, dst = 771})
panel:addChild(energy_bg_3)

--Create lb_energy
local lb_energy = ccui.Text:create()
lb_energy:ignoreContentAdaptWithSize(true)
lb_energy:setTextAreaSize({width = 0, height = 0})
lb_energy:setFontSize(28)
lb_energy:setString([[10000]])
lb_energy:enableShadow({r = 34, g = 93, b = 104, a = 255}, {width = 1, height = -1}, 0)
lb_energy:setLayoutComponentEnabled(true)
lb_energy:setName("lb_energy")
lb_energy:setTag(607)
lb_energy:setCascadeColorEnabled(true)
lb_energy:setCascadeOpacityEnabled(true)
lb_energy:setPosition(132.9890, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_energy)
layout:setPositionPercentX(0.5635)
layout:setPositionPercentY(0.5167)
layout:setPercentWidth(0.3305)
layout:setPercentHeight(0.5333)
layout:setSize({width = 78.0000, height = 32.0000})
layout:setLeftMargin(93.9890)
layout:setRightMargin(64.0111)
layout:setTopMargin(13.0000)
layout:setBottomMargin(15.0000)
energy_bg_3:addChild(lb_energy)

--Create btn_buy_energy
local btn_buy_energy = ccui.Button:create()
btn_buy_energy:ignoreContentAdaptWithSize(false)
btn_buy_energy:loadTextureNormal("ui/tetris/power/pay_bg.png",0)
btn_buy_energy:loadTexturePressed("ui/tetris/power/pay_bg.png",0)
btn_buy_energy:loadTextureDisabled("ui/tetris/power/pay_bg.png",0)
btn_buy_energy:setTitleFontSize(14)
btn_buy_energy:setTitleColor({r = 65, g = 65, b = 70})
btn_buy_energy:setScale9Enabled(true)
btn_buy_energy:setCapInsets({x = 15, y = 11, width = 15, height = 23})
btn_buy_energy:setLayoutComponentEnabled(true)
btn_buy_energy:setName("btn_buy_energy")
btn_buy_energy:setTag(609)
btn_buy_energy:setCascadeColorEnabled(true)
btn_buy_energy:setCascadeOpacityEnabled(true)
btn_buy_energy:setPosition(240.3605, 31.3040)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_buy_energy)
layout:setPositionPercentX(1.0185)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(0.1907)
layout:setPercentHeight(0.7500)
layout:setSize({width = 45.0000, height = 45.0000})
layout:setLeftMargin(217.8605)
layout:setRightMargin(-26.8605)
layout:setTopMargin(6.1960)
layout:setBottomMargin(8.8040)
energy_bg_3:addChild(btn_buy_energy)

--Create item_bg_2
local item_bg_2 = cc.Sprite:create("ui/tetris/power/item_bg.png")
item_bg_2:setName("item_bg_2")
item_bg_2:setTag(604)
item_bg_2:setCascadeColorEnabled(true)
item_bg_2:setCascadeOpacityEnabled(true)
item_bg_2:setPosition(467.6490, 1093.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(item_bg_2)
layout:setPositionPercentX(0.7307)
layout:setPositionPercentY(0.9621)
layout:setPercentWidth(0.3688)
layout:setPercentHeight(0.0528)
layout:setSize({width = 236.0000, height = 60.0000})
layout:setLeftMargin(349.6490)
layout:setRightMargin(54.3510)
layout:setTopMargin(13.0000)
layout:setBottomMargin(1063.0000)
item_bg_2:setBlendFunc({src = 1, dst = 771})
panel:addChild(item_bg_2)

--Create lb_item
local lb_item = ccui.Text:create()
lb_item:ignoreContentAdaptWithSize(true)
lb_item:setTextAreaSize({width = 0, height = 0})
lb_item:setFontSize(28)
lb_item:setString([[10000]])
lb_item:enableShadow({r = 34, g = 93, b = 104, a = 255}, {width = 1, height = -1}, 0)
lb_item:setLayoutComponentEnabled(true)
lb_item:setName("lb_item")
lb_item:setTag(608)
lb_item:setCascadeColorEnabled(true)
lb_item:setCascadeOpacityEnabled(true)
lb_item:setPosition(135.9896, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_item)
layout:setPositionPercentX(0.5762)
layout:setPositionPercentY(0.5167)
layout:setPercentWidth(0.3305)
layout:setPercentHeight(0.5333)
layout:setSize({width = 78.0000, height = 32.0000})
layout:setLeftMargin(96.9896)
layout:setRightMargin(61.0104)
layout:setTopMargin(13.0000)
layout:setBottomMargin(15.0000)
item_bg_2:addChild(lb_item)

--Create btn_buy_item
local btn_buy_item = ccui.Button:create()
btn_buy_item:ignoreContentAdaptWithSize(false)
btn_buy_item:loadTextureNormal("ui/tetris/power/pay_bg.png",0)
btn_buy_item:loadTexturePressed("ui/tetris/power/pay_bg.png",0)
btn_buy_item:loadTextureDisabled("ui/tetris/power/pay_bg.png",0)
btn_buy_item:setTitleFontSize(14)
btn_buy_item:setTitleColor({r = 65, g = 65, b = 70})
btn_buy_item:setScale9Enabled(true)
btn_buy_item:setCapInsets({x = 15, y = 11, width = 15, height = 23})
btn_buy_item:setLayoutComponentEnabled(true)
btn_buy_item:setName("btn_buy_item")
btn_buy_item:setTag(606)
btn_buy_item:setCascadeColorEnabled(true)
btn_buy_item:setCascadeOpacityEnabled(true)
btn_buy_item:setPosition(241.3602, 31.3038)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_buy_item)
layout:setPositionPercentX(1.0227)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(0.1907)
layout:setPercentHeight(0.7500)
layout:setSize({width = 45.0000, height = 45.0000})
layout:setLeftMargin(218.8602)
layout:setRightMargin(-27.8602)
layout:setTopMargin(6.1962)
layout:setBottomMargin(8.8038)
item_bg_2:addChild(btn_buy_item)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

