--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6281)
layout:setPercentHeight(0.0836)
layout:setSize({width = 402.0000, height = 95.0000})
layout:setLeftMargin(119.0000)
layout:setRightMargin(119.0000)
layout:setTopMargin(520.5000)
layout:setBottomMargin(520.5000)
Scene:addChild(panel)

--Create btn_buy
local btn_buy = ccui.Button:create()
btn_buy:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_buy:loadTextureNormal("btn_buy.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_buy:loadTexturePressed("btn_buy.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_buy:loadTextureDisabled("btn_buy.png",1)
btn_buy:setTitleFontSize(28)
btn_buy:setScale9Enabled(true)
btn_buy:setCapInsets({x = 15, y = 11, width = 140, height = 38})
btn_buy:setLayoutComponentEnabled(true)
btn_buy:setName("btn_buy")
btn_buy:setTag(175)
btn_buy:setCascadeColorEnabled(true)
btn_buy:setCascadeOpacityEnabled(true)
btn_buy:setPosition(294.3769, 45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_buy)
layout:setPositionPercentX(0.7323)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.4229)
layout:setPercentHeight(0.6316)
layout:setSize({width = 170.0000, height = 60.0000})
layout:setLeftMargin(209.3769)
layout:setRightMargin(22.6231)
layout:setTopMargin(20.0000)
layout:setBottomMargin(15.0000)
panel:addChild(btn_buy)

--Create sp_diam
local sp_diam = cc.Sprite:create("ui/shop/icon_diam2.png")
sp_diam:setName("sp_diam")
sp_diam:setTag(159)
sp_diam:setCascadeColorEnabled(true)
sp_diam:setCascadeOpacityEnabled(true)
sp_diam:setPosition(118.2851, 44.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_diam)
layout:setPositionPercentX(0.2942)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.2239)
layout:setPercentHeight(0.9474)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(73.2851)
layout:setRightMargin(238.7149)
layout:setTopMargin(5.0002)
layout:setBottomMargin(-0.0002)
sp_diam:setBlendFunc({src = 1, dst = 771})
panel:addChild(sp_diam)

--Create lb_diam
local lb_diam = ccui.Text:create()
lb_diam:ignoreContentAdaptWithSize(true)
lb_diam:setTextAreaSize({width = 0, height = 0})
lb_diam:setFontSize(32)
lb_diam:setString([[4880]])
lb_diam:setTextHorizontalAlignment(2)
lb_diam:enableShadow({r = 64, g = 57, b = 53, a = 255}, {width = 1, height = -1}, 0)
lb_diam:setLayoutComponentEnabled(true)
lb_diam:setName("lb_diam")
lb_diam:setTag(161)
lb_diam:setCascadeColorEnabled(true)
lb_diam:setCascadeOpacityEnabled(true)
lb_diam:setAnchorPoint(1.0000, 0.5000)
lb_diam:setPosition(74.6830, 44.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_diam)
layout:setPositionPercentX(0.1858)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.1592)
layout:setPercentHeight(0.3474)
layout:setSize({width = 64.0000, height = 33.0000})
layout:setLeftMargin(10.6830)
layout:setRightMargin(327.3170)
layout:setTopMargin(33.5002)
layout:setBottomMargin(28.4999)
panel:addChild(lb_diam)

--Create lb_price
local lb_price = ccui.Text:create()
lb_price:ignoreContentAdaptWithSize(true)
lb_price:setTextAreaSize({width = 0, height = 0})
lb_price:setFontSize(32)
lb_price:setString([[4880]])
lb_price:setTextHorizontalAlignment(2)
lb_price:enableShadow({r = 64, g = 57, b = 53, a = 255}, {width = 1, height = -1}, 0)
lb_price:setLayoutComponentEnabled(true)
lb_price:setName("lb_price")
lb_price:setTag(169)
lb_price:setCascadeColorEnabled(true)
lb_price:setCascadeOpacityEnabled(true)
lb_price:setAnchorPoint(1.0000, 0.5000)
lb_price:setPosition(324.7129, 45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_price)
layout:setPositionPercentX(0.8077)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.1592)
layout:setPercentHeight(0.3474)
layout:setSize({width = 64.0000, height = 33.0000})
layout:setLeftMargin(260.7129)
layout:setRightMargin(77.2871)
layout:setTopMargin(33.5000)
layout:setBottomMargin(28.5000)
panel:addChild(lb_price)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

