--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(85)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3313)
layout:setPercentHeight(0.2465)
layout:setSize({width = 852.0000, height = 280.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
layout:setTopMargin(996.0000)
layout:setBottomMargin(-140.0000)
Scene:addChild(panel)

--Create intro_bg
local intro_bg = cc.Sprite:create("ui/bg/intro_bg.png")
intro_bg:setName("intro_bg")
intro_bg:setTag(170)
intro_bg:setCascadeColorEnabled(true)
intro_bg:setCascadeOpacityEnabled(true)
intro_bg:setPosition(426.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(intro_bg)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.9643)
layout:setSize({width = 852.0000, height = 270.0000})
layout:setTopMargin(145.0000)
layout:setBottomMargin(-135.0000)
intro_bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(intro_bg)

--Create lb_intro
local lb_intro = ccui.Text:create()
lb_intro:ignoreContentAdaptWithSize(true)
lb_intro:setTextAreaSize({width = 0, height = 0})
lb_intro:setFontSize(38)
lb_intro:setString([[收集星星]])
lb_intro:enableShadow({r = 11, g = 29, b = 26, a = 255}, {width = 1, height = -1}, 0)
lb_intro:setLayoutComponentEnabled(true)
lb_intro:setName("lb_intro")
lb_intro:setTag(171)
lb_intro:setCascadeColorEnabled(true)
lb_intro:setCascadeOpacityEnabled(true)
lb_intro:setPosition(426.0000, -38.0000)
lb_intro:setTextColor({r = 72, g = 64, b = 54})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_intro)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.1357)
layout:setPercentWidth(0.1784)
layout:setPercentHeight(0.1357)
layout:setSize({width = 152.0000, height = 38.0000})
layout:setLeftMargin(350.0000)
layout:setRightMargin(350.0000)
layout:setTopMargin(299.0000)
layout:setBottomMargin(-57.0000)
panel:addChild(lb_intro)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

