--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create btn_multiplayer
local btn_multiplayer = ccui.Button:create()
btn_multiplayer:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_multiplayer:loadTextureNormal("green_btn.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_multiplayer:loadTexturePressed("green_btn.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_multiplayer:loadTextureDisabled("green_btn.png",1)
btn_multiplayer:setTitleFontSize(28)
btn_multiplayer:setTitleText("联网对战")
btn_multiplayer:setTitleColor({r = 255, g = 255, b = 0})
btn_multiplayer:setScale9Enabled(true)
btn_multiplayer:setCapInsets({x = 15, y = 11, width = 168, height = 48})
btn_multiplayer:setLayoutComponentEnabled(true)
btn_multiplayer:setName("btn_multiplayer")
btn_multiplayer:setTag(58)
btn_multiplayer:setCascadeColorEnabled(true)
btn_multiplayer:setCascadeOpacityEnabled(true)
btn_multiplayer:setPosition(493.4147, 194.7733)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_multiplayer)
layout:setPositionPercentX(0.7710)
layout:setPositionPercentY(0.1715)
layout:setPercentWidth(0.3094)
layout:setPercentHeight(0.0616)
layout:setSize({width = 198.0000, height = 70.0000})
layout:setLeftMargin(394.4147)
layout:setRightMargin(47.5853)
layout:setTopMargin(906.2267)
layout:setBottomMargin(159.7733)
panel:addChild(btn_multiplayer)

--Create bg_input
local bg_input = ccui.ImageView:create()
bg_input:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
bg_input:loadTexture("input_bg.png",1)
bg_input:setScale9Enabled(true)
bg_input:setCapInsets({x = 5, y = 5, width = 21, height = 21})
bg_input:setTouchEnabled(true);
bg_input:setLayoutComponentEnabled(true)
bg_input:setName("bg_input")
bg_input:setTag(98)
bg_input:setCascadeColorEnabled(true)
bg_input:setCascadeOpacityEnabled(true)
bg_input:setPosition(231.7774, 194.7733)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_input)
layout:setPositionPercentX(0.3622)
layout:setPositionPercentY(0.1715)
layout:setPercentWidth(0.5469)
layout:setPercentHeight(0.0616)
layout:setSize({width = 350.0000, height = 70.0000})
layout:setLeftMargin(56.7774)
layout:setRightMargin(233.2226)
layout:setTopMargin(906.2267)
layout:setBottomMargin(159.7733)
panel:addChild(bg_input)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

