--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create scene_bg
local scene_bg = ccui.ImageView:create()
scene_bg:ignoreContentAdaptWithSize(false)
scene_bg:loadTexture("ui/tetris/scene_bg.png",0)
scene_bg:setLayoutComponentEnabled(true)
scene_bg:setName("scene_bg")
scene_bg:setTag(64)
scene_bg:setCascadeColorEnabled(true)
scene_bg:setCascadeOpacityEnabled(true)
scene_bg:setPosition(316.8754, 571.1373)
layout = ccui.LayoutComponent:bindLayoutComponent(scene_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4951)
layout:setPositionPercentY(0.5028)
layout:setPercentWidth(1.3313)
layout:setPercentHeight(1.0000)
layout:setSize({width = 852.0000, height = 1136.0000})
layout:setLeftMargin(-109.1246)
layout:setRightMargin(-102.8754)
layout:setTopMargin(-3.1373)
layout:setBottomMargin(3.1373)
panel:addChild(scene_bg)

--Create btn_single
local btn_single = ccui.Button:create()
btn_single:ignoreContentAdaptWithSize(false)
btn_single:loadTextureNormal("ui/button/green_btn.png",0)
btn_single:loadTexturePressed("ui/button/green_btn.png",0)
btn_single:loadTextureDisabled("ui/button/green_btn.png",0)
btn_single:setTitleFontSize(28)
btn_single:setTitleText("单机生涯")
btn_single:setTitleColor({r = 255, g = 255, b = 0})
btn_single:setScale9Enabled(true)
btn_single:setCapInsets({x = 15, y = 11, width = 168, height = 48})
btn_single:setLayoutComponentEnabled(true)
btn_single:setName("btn_single")
btn_single:setTag(57)
btn_single:setCascadeColorEnabled(true)
btn_single:setCascadeOpacityEnabled(true)
btn_single:setPosition(300.8522, 685.2758)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_single)
layout:setPositionPercentX(0.4701)
layout:setPositionPercentY(0.6032)
layout:setPercentWidth(0.3094)
layout:setPercentHeight(0.0616)
layout:setSize({width = 198.0000, height = 70.0000})
layout:setLeftMargin(201.8522)
layout:setRightMargin(240.1478)
layout:setTopMargin(415.7242)
layout:setBottomMargin(650.2758)
panel:addChild(btn_single)

--Create btn_multiplayer
local btn_multiplayer = ccui.Button:create()
btn_multiplayer:ignoreContentAdaptWithSize(false)
btn_multiplayer:loadTextureNormal("ui/button/green_btn.png",0)
btn_multiplayer:loadTexturePressed("ui/button/green_btn.png",0)
btn_multiplayer:loadTextureDisabled("ui/button/green_btn.png",0)
btn_multiplayer:setTitleFontSize(28)
btn_multiplayer:setTitleText("联网对战")
btn_multiplayer:setTitleColor({r = 255, g = 255, b = 0})
btn_multiplayer:setScale9Enabled(true)
btn_multiplayer:setCapInsets({x = 15, y = 11, width = 168, height = 48})
btn_multiplayer:setLayoutComponentEnabled(true)
btn_multiplayer:setName("btn_multiplayer")
btn_multiplayer:setTag(58)
btn_multiplayer:setCascadeColorEnabled(true)
btn_multiplayer:setCascadeOpacityEnabled(true)
btn_multiplayer:setPosition(300.8522, 563.8486)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_multiplayer)
layout:setPositionPercentX(0.4701)
layout:setPositionPercentY(0.4963)
layout:setPercentWidth(0.3094)
layout:setPercentHeight(0.0616)
layout:setSize({width = 198.0000, height = 70.0000})
layout:setLeftMargin(201.8522)
layout:setRightMargin(240.1478)
layout:setTopMargin(537.1514)
layout:setBottomMargin(528.8486)
panel:addChild(btn_multiplayer)

--Create bg_input
local bg_input = ccui.ImageView:create()
bg_input:ignoreContentAdaptWithSize(false)
bg_input:loadTexture("res/input_bg.png",0)
bg_input:setScale9Enabled(true)
bg_input:setCapInsets({x = 5, y = 5, width = 21, height = 21})
bg_input:setTouchEnabled(true);
bg_input:setLayoutComponentEnabled(true)
bg_input:setName("bg_input")
bg_input:setTag(98)
bg_input:setCascadeColorEnabled(true)
bg_input:setCascadeOpacityEnabled(true)
bg_input:setPosition(300.8500, 445.7100)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_input)
layout:setPositionPercentX(0.4701)
layout:setPositionPercentY(0.3924)
layout:setPercentWidth(0.3906)
layout:setPercentHeight(0.0616)
layout:setSize({width = 250.0000, height = 70.0000})
layout:setLeftMargin(175.8500)
layout:setRightMargin(214.1500)
layout:setTopMargin(655.2900)
layout:setBottomMargin(410.7100)
panel:addChild(bg_input)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

