--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(34)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 567.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
layout:setTopMargin(0.0002)
layout:setBottomMargin(-0.0002)
Scene:addChild(panel)

--Create bg
local bg = cc.Sprite:create("ui/loading/loading_bg.png")
bg:setName("bg")
bg:setTag(138)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3313)
layout:setPercentHeight(1.0000)
layout:setSize({width = 852.0000, height = 1136.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
bg:setBlendFunc({src = 770, dst = 771})
panel:addChild(bg)

--Create lb_tips
local lb_tips = ccui.Text:create()
lb_tips:ignoreContentAdaptWithSize(true)
lb_tips:setTextAreaSize({width = 0, height = 0})
lb_tips:setFontSize(32)
lb_tips:setString([[正在登录游戏]])
lb_tips:enableShadow({r = 110, g = 110, b = 110, a = 255}, {width = 1, height = -1}, 0)
lb_tips:setLayoutComponentEnabled(true)
lb_tips:setName("lb_tips")
lb_tips:setTag(4)
lb_tips:setCascadeColorEnabled(true)
lb_tips:setCascadeOpacityEnabled(true)
lb_tips:setPosition(320.0000, 381.4025)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_tips)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3357)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0290)
layout:setSize({width = 192.0000, height = 33.0000})
layout:setLeftMargin(224.0000)
layout:setRightMargin(224.0000)
layout:setTopMargin(738.0975)
layout:setBottomMargin(364.9025)
panel:addChild(lb_tips)

--Create progress
local progress = ccui.Slider:create()
progress:ignoreContentAdaptWithSize(false)
progress:loadBarTexture("ui/loading/loading_progress_bg.png",0)
progress:loadProgressBarTexture("ui/loading/loading_progress.png",0)
progress:loadSlidBallTextureNormal("Default/SliderNode_Normal.png",0)
progress:loadSlidBallTexturePressed("Default/SliderNode_Press.png",0)
progress:loadSlidBallTextureDisabled("Default/SliderNode_Disable.png",0)
progress:setPercent(50)
progress:setLayoutComponentEnabled(true)
progress:setName("progress")
progress:setTag(94)
progress:setCascadeColorEnabled(true)
progress:setCascadeOpacityEnabled(true)
progress:setPosition(320.0000, 338.5658)
layout = ccui.LayoutComponent:bindLayoutComponent(progress)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2980)
layout:setPercentWidth(0.7813)
layout:setPercentHeight(0.0264)
layout:setSize({width = 500.0000, height = 30.0000})
layout:setLeftMargin(70.0000)
layout:setRightMargin(70.0000)
layout:setTopMargin(782.4342)
layout:setBottomMargin(323.5658)
panel:addChild(progress)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

