--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create bg
local bg = cc.Sprite:create("ui/tips/tips_bg.png")
bg:setName("bg")
bg:setTag(77)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9766)
layout:setPercentHeight(0.4137)
layout:setSize({width = 625.0000, height = 470.0000})
layout:setLeftMargin(7.5000)
layout:setRightMargin(7.5000)
layout:setTopMargin(333.0000)
layout:setBottomMargin(333.0000)
bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(bg)

--Create inner_bg
local inner_bg = cc.Sprite:create("ui/tips/tips_inner_bg.png")
inner_bg:setName("inner_bg")
inner_bg:setTag(78)
inner_bg:setCascadeColorEnabled(true)
inner_bg:setCascadeOpacityEnabled(true)
inner_bg:setPosition(320.0001, 545.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(inner_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4798)
layout:setPercentWidth(0.7031)
layout:setPercentHeight(0.1320)
layout:setSize({width = 450.0000, height = 150.0000})
layout:setLeftMargin(95.0001)
layout:setRightMargin(94.9999)
layout:setTopMargin(515.9999)
layout:setBottomMargin(470.0001)
inner_bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(inner_bg)

--Create btn_ok
local btn_ok = ccui.Button:create()
btn_ok:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_ok:loadTextureNormal("btn_ok.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_ok:loadTexturePressed("btn_ok.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_ok:loadTextureDisabled("btn_ok.png",1)
btn_ok:setTitleFontSize(14)
btn_ok:setTitleColor({r = 65, g = 65, b = 70})
btn_ok:setScale9Enabled(true)
btn_ok:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_ok:setLayoutComponentEnabled(true)
btn_ok:setName("btn_ok")
btn_ok:setTag(79)
btn_ok:setCascadeColorEnabled(true)
btn_ok:setCascadeOpacityEnabled(true)
btn_ok:setPosition(320.0002, 432.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_ok)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3803)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0002)
layout:setRightMargin(173.9998)
layout:setTopMargin(660.9998)
layout:setBottomMargin(389.0002)
panel:addChild(btn_ok)

--Create icon
local icon = cc.Sprite:create("Default/Sprite.png")
icon:setName("icon")
icon:setTag(80)
icon:setCascadeColorEnabled(true)
icon:setCascadeOpacityEnabled(true)
icon:setPosition(320.0000, 670.9463)
layout = ccui.LayoutComponent:bindLayoutComponent(icon)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5906)
layout:setPercentWidth(0.0719)
layout:setPercentHeight(0.0405)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(297.0000)
layout:setRightMargin(297.0000)
layout:setTopMargin(442.0537)
layout:setBottomMargin(647.9463)
icon:setBlendFunc({src = 1, dst = 771})
panel:addChild(icon)

--Create lb_title
local lb_title = ccui.Text:create()
lb_title:ignoreContentAdaptWithSize(true)
lb_title:setTextAreaSize({width = 0, height = 0})
lb_title:setFontSize(28)
lb_title:setString([[购买失败]])
lb_title:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 1, height = -1}, 0)
lb_title:setLayoutComponentEnabled(true)
lb_title:setName("lb_title")
lb_title:setTag(81)
lb_title:setCascadeColorEnabled(true)
lb_title:setCascadeOpacityEnabled(true)
lb_title:setPosition(320.0000, 761.7169)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6705)
layout:setPercentWidth(0.1750)
layout:setPercentHeight(0.0246)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(264.0000)
layout:setRightMargin(264.0000)
layout:setTopMargin(360.2831)
layout:setBottomMargin(747.7169)
panel:addChild(lb_title)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureNormal("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTexturePressed("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureDisabled("close.png",1)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 35, height = 43})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(82)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(551.2875, 759.6870)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8614)
layout:setPositionPercentY(0.6687)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0572)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(518.7875)
layout:setRightMargin(56.2125)
layout:setTopMargin(343.8130)
layout:setBottomMargin(727.1870)
panel:addChild(btn_close)

--Create lb_info
local lb_info = ccui.Text:create()
lb_info:ignoreContentAdaptWithSize(true)
lb_info:setTextAreaSize({width = 0, height = 0})
lb_info:setFontSize(26)
lb_info:setString([[商店无法使用
请重试一次]])
lb_info:enableShadow({r = 61, g = 136, b = 171, a = 255}, {width = 1, height = -1}, 0)
lb_info:setLayoutComponentEnabled(true)
lb_info:setName("lb_info")
lb_info:setTag(83)
lb_info:setCascadeColorEnabled(true)
lb_info:setCascadeOpacityEnabled(true)
lb_info:setPosition(352.7506, 542.3608)
lb_info:setTextColor({r = 225, g = 139, b = 144})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_info)
layout:setPositionPercentX(0.5512)
layout:setPositionPercentY(0.4774)
layout:setPercentWidth(0.2438)
layout:setPercentHeight(0.0458)
layout:setSize({width = 156.0000, height = 52.0000})
layout:setLeftMargin(274.7506)
layout:setRightMargin(209.2494)
layout:setTopMargin(567.6392)
layout:setBottomMargin(516.3608)
panel:addChild(lb_info)

--Create icon_info
local icon_info = cc.Sprite:create("Default/Sprite.png")
icon_info:setName("icon_info")
icon_info:setTag(85)
icon_info:setCascadeColorEnabled(true)
icon_info:setCascadeOpacityEnabled(true)
icon_info:setPosition(197.3533, 542.3607)
layout = ccui.LayoutComponent:bindLayoutComponent(icon_info)
layout:setPositionPercentX(0.3084)
layout:setPositionPercentY(0.4774)
layout:setPercentWidth(0.0719)
layout:setPercentHeight(0.0405)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(174.3533)
layout:setRightMargin(419.6467)
layout:setTopMargin(570.6393)
layout:setBottomMargin(519.3607)
icon_info:setBlendFunc({src = 1, dst = 771})
panel:addChild(icon_info)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

