--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(115)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 640.0000, height = 1136.0000})
Scene:addChild(panel)

--Create bg
local bg = cc.Sprite:create("ui/tips/tips_bg.png")
bg:setName("bg")
bg:setTag(77)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(320.0000, 568.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9766)
layout:setPercentHeight(0.4137)
layout:setSize({width = 625.0000, height = 470.0000})
layout:setLeftMargin(7.5000)
layout:setRightMargin(7.5000)
layout:setTopMargin(333.0000)
layout:setBottomMargin(333.0000)
bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(bg)

--Create inner_bg
local inner_bg = cc.Sprite:create("ui/tips/tips_inner_bg.png")
inner_bg:setName("inner_bg")
inner_bg:setTag(78)
inner_bg:setCascadeColorEnabled(true)
inner_bg:setCascadeOpacityEnabled(true)
inner_bg:setPosition(328.9771, 652.7206)
layout = ccui.LayoutComponent:bindLayoutComponent(inner_bg)
layout:setPositionPercentX(0.5140)
layout:setPositionPercentY(0.5746)
layout:setPercentWidth(0.7031)
layout:setPercentHeight(0.1320)
layout:setSize({width = 450.0000, height = 150.0000})
layout:setLeftMargin(103.9771)
layout:setRightMargin(86.0229)
layout:setTopMargin(408.2794)
layout:setBottomMargin(577.7206)
inner_bg:setBlendFunc({src = 1, dst = 771})
panel:addChild(inner_bg)

--Create icon_title
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
local icon_title = cc.Sprite:createWithSpriteFrameName("energy_bg2.png")
icon_title:setName("icon_title")
icon_title:setTag(96)
icon_title:setCascadeColorEnabled(true)
icon_title:setCascadeOpacityEnabled(true)
icon_title:setPosition(318.2641, 761.0237)
layout = ccui.LayoutComponent:bindLayoutComponent(icon_title)
layout:setPositionPercentX(0.4973)
layout:setPositionPercentY(0.6699)
layout:setPercentWidth(0.0688)
layout:setPercentHeight(0.0387)
layout:setSize({width = 44.0000, height = 44.0000})
layout:setLeftMargin(296.2641)
layout:setRightMargin(299.7359)
layout:setTopMargin(352.9763)
layout:setBottomMargin(739.0237)
icon_title:setBlendFunc({src = 1, dst = 771})
panel:addChild(icon_title)

--Create lb_title
local lb_title = ccui.Text:create()
lb_title:ignoreContentAdaptWithSize(true)
lb_title:setTextAreaSize({width = 0, height = 0})
lb_title:setFontSize(28)
lb_title:setString([[4]])
lb_title:enableShadow({r = 0, g = 0, b = 0, a = 255}, {width = 1, height = -1}, 0)
lb_title:setLayoutComponentEnabled(true)
lb_title:setName("lb_title")
lb_title:setTag(81)
lb_title:setCascadeColorEnabled(true)
lb_title:setCascadeOpacityEnabled(true)
lb_title:setAnchorPoint(0.0000, 0.5000)
lb_title:setPosition(334.9827, 761.0237)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_title)
layout:setPositionPercentX(0.5234)
layout:setPositionPercentY(0.6699)
layout:setPercentWidth(0.0219)
layout:setPercentHeight(0.0246)
layout:setSize({width = 14.0000, height = 28.0000})
layout:setLeftMargin(334.9827)
layout:setRightMargin(291.0173)
layout:setTopMargin(360.9763)
layout:setBottomMargin(747.0237)
panel:addChild(lb_title)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureNormal("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTexturePressed("close.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_close:loadTextureDisabled("close.png",1)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 35, height = 43})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(82)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(551.2875, 759.6870)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8614)
layout:setPositionPercentY(0.6687)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0572)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(518.7875)
layout:setRightMargin(56.2125)
layout:setTopMargin(343.8130)
layout:setBottomMargin(727.1870)
panel:addChild(btn_close)

--Create lb_info
local lb_info = ccui.Text:create()
lb_info:ignoreContentAdaptWithSize(true)
lb_info:setTextAreaSize({width = 0, height = 0})
lb_info:setFontSize(26)
lb_info:setString([[体力恢复时间]])
lb_info:enableShadow({r = 26, g = 26, b = 26, a = 255}, {width = 1, height = -1}, 0)
lb_info:setLayoutComponentEnabled(true)
lb_info:setName("lb_info")
lb_info:setTag(83)
lb_info:setCascadeColorEnabled(true)
lb_info:setCascadeOpacityEnabled(true)
lb_info:setPosition(320.0000, 674.0193)
lb_info:setTextColor({r = 25, g = 76, b = 94})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_info)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5933)
layout:setPercentWidth(0.2438)
layout:setPercentHeight(0.0229)
layout:setSize({width = 156.0000, height = 26.0000})
layout:setLeftMargin(242.0000)
layout:setRightMargin(242.0000)
layout:setTopMargin(448.9807)
layout:setBottomMargin(661.0193)
panel:addChild(lb_info)

--Create lb_time
local lb_time = ccui.Text:create()
lb_time:ignoreContentAdaptWithSize(true)
lb_time:setTextAreaSize({width = 0, height = 0})
lb_time:setFontSize(26)
lb_time:setString([[14:59]])
lb_time:enableShadow({r = 26, g = 26, b = 26, a = 255}, {width = 1, height = -1}, 0)
lb_time:setLayoutComponentEnabled(true)
lb_time:setName("lb_time")
lb_time:setTag(97)
lb_time:setCascadeColorEnabled(true)
lb_time:setCascadeOpacityEnabled(true)
lb_time:setPosition(320.0000, 636.0931)
lb_time:setTextColor({r = 25, g = 76, b = 94})
layout = ccui.LayoutComponent:bindLayoutComponent(lb_time)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5599)
layout:setPercentWidth(0.1016)
layout:setPercentHeight(0.0229)
layout:setSize({width = 65.0000, height = 26.0000})
layout:setLeftMargin(287.5000)
layout:setRightMargin(287.5000)
layout:setTopMargin(486.9069)
layout:setBottomMargin(623.0931)
panel:addChild(lb_time)

--Create btn_buy
local btn_buy = ccui.Button:create()
btn_buy:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_buy:loadTextureNormal("btn_buy_energy.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_buy:loadTexturePressed("btn_buy_energy.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_buy:loadTextureDisabled("btn_buy_energy.png",1)
btn_buy:setTitleFontSize(14)
btn_buy:setTitleColor({r = 65, g = 65, b = 70})
btn_buy:setScale9Enabled(true)
btn_buy:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_buy:setLayoutComponentEnabled(true)
btn_buy:setName("btn_buy")
btn_buy:setTag(79)
btn_buy:setCascadeColorEnabled(true)
btn_buy:setCascadeOpacityEnabled(true)
btn_buy:setPosition(320.0003, 435.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_buy)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3829)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0003)
layout:setRightMargin(173.9997)
layout:setTopMargin(658.0000)
layout:setBottomMargin(392.0000)
panel:addChild(btn_buy)

--Create btn_watch
local btn_watch = ccui.Button:create()
btn_watch:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_watch:loadTextureNormal("btn_watch_video.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_watch:loadTexturePressed("btn_watch_video.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("ui/plist/common.plist")
btn_watch:loadTextureDisabled("btn_watch_video.png",1)
btn_watch:setTitleFontSize(14)
btn_watch:setTitleColor({r = 65, g = 65, b = 70})
btn_watch:setScale9Enabled(true)
btn_watch:setCapInsets({x = 15, y = 11, width = 262, height = 64})
btn_watch:setLayoutComponentEnabled(true)
btn_watch:setName("btn_watch")
btn_watch:setTag(99)
btn_watch:setCascadeColorEnabled(true)
btn_watch:setCascadeOpacityEnabled(true)
btn_watch:setPosition(320.0003, 534.7155)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_watch)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4707)
layout:setPercentWidth(0.4563)
layout:setPercentHeight(0.0757)
layout:setSize({width = 292.0000, height = 86.0000})
layout:setLeftMargin(174.0003)
layout:setRightMargin(173.9997)
layout:setTopMargin(558.2845)
layout:setBottomMargin(491.7155)
panel:addChild(btn_watch)

--Create lb_price
local lb_price = ccui.Text:create()
lb_price:ignoreContentAdaptWithSize(true)
lb_price:setTextAreaSize({width = 0, height = 0})
lb_price:setFontSize(28)
lb_price:setString([[5]])
lb_price:setLayoutComponentEnabled(true)
lb_price:setName("lb_price")
lb_price:setTag(165)
lb_price:setCascadeColorEnabled(true)
lb_price:setCascadeOpacityEnabled(true)
lb_price:setAnchorPoint(0.0000, 0.5000)
lb_price:setPosition(249.0958, 435.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lb_price)
layout:setPositionPercentX(0.3892)
layout:setPositionPercentY(0.3829)
layout:setPercentWidth(0.0219)
layout:setPercentHeight(0.0246)
layout:setSize({width = 14.0000, height = 28.0000})
layout:setLeftMargin(249.0958)
layout:setRightMargin(376.9042)
layout:setTopMargin(687.0000)
layout:setBottomMargin(421.0000)
panel:addChild(lb_price)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

